import { Building2, Landmark, TreePine, Plane, Train, Ship } from "lucide-react";

export const westBengalLocations = [
  // ==================== KOLKATA ====================
  { name: "Howrah Station, Kolkata", icon: Train, category: "Railway Station", district: "Howrah" },
  { name: "Sealdah Station, Kolkata", icon: Train, category: "Railway Station", district: "Kolkata" },
  { name: "Kolkata Station (Chitpur)", icon: Train, category: "Railway Station", district: "Kolkata" },
  { name: "Santragachi Station, Howrah", icon: Train, category: "Railway Station", district: "Howrah" },
  { name: "Shalimar Station, Howrah", icon: Train, category: "Railway Station", district: "Howrah" },
  { name: "Netaji Subhas Chandra Bose Airport, Kolkata", icon: Plane, category: "Airport", district: "North 24 Parganas" },
  { name: "Victoria Memorial, Kolkata", icon: Landmark, category: "Landmark", district: "Kolkata" },
  { name: "Dakshineswar Kali Temple, Kolkata", icon: Landmark, category: "Temple", district: "North 24 Parganas" },
  { name: "Kalighat Temple, Kolkata", icon: Landmark, category: "Temple", district: "Kolkata" },
  { name: "Belur Math, Howrah", icon: Landmark, category: "Temple", district: "Howrah" },
  { name: "Indian Museum, Kolkata", icon: Landmark, category: "Museum", district: "Kolkata" },
  { name: "Science City, Kolkata", icon: Building2, category: "Landmark", district: "Kolkata" },
  { name: "Eco Park, New Town", icon: TreePine, category: "Park", district: "North 24 Parganas" },
  { name: "Nicco Park, Salt Lake", icon: TreePine, category: "Park", district: "North 24 Parganas" },
  { name: "Birla Planetarium, Kolkata", icon: Landmark, category: "Landmark", district: "Kolkata" },
  { name: "Eden Gardens, Kolkata", icon: Landmark, category: "Stadium", district: "Kolkata" },
  { name: "Salt Lake Stadium, Kolkata", icon: Landmark, category: "Stadium", district: "North 24 Parganas" },
  { name: "Netaji Indoor Stadium, Kolkata", icon: Landmark, category: "Stadium", district: "Kolkata" },
  { name: "Princep Ghat, Kolkata", icon: Landmark, category: "Landmark", district: "Kolkata" },
  { name: "Millennium Park, Kolkata", icon: TreePine, category: "Park", district: "Kolkata" },
  { name: "Rabindra Sadan, Kolkata", icon: Landmark, category: "Landmark", district: "Kolkata" },
  { name: "Nandan, Kolkata", icon: Landmark, category: "Landmark", district: "Kolkata" },
  { name: "Academy of Fine Arts, Kolkata", icon: Landmark, category: "Landmark", district: "Kolkata" },
  
  // Kolkata Areas
  { name: "Park Street, Kolkata", icon: Building2, category: "Area", district: "Kolkata" },
  { name: "Esplanade, Kolkata", icon: Building2, category: "Area", district: "Kolkata" },
  { name: "Salt Lake City (Sector I), Kolkata", icon: Building2, category: "Area", district: "North 24 Parganas" },
  { name: "Salt Lake City (Sector II), Kolkata", icon: Building2, category: "Area", district: "North 24 Parganas" },
  { name: "Salt Lake City (Sector III), Kolkata", icon: Building2, category: "Area", district: "North 24 Parganas" },
  { name: "Salt Lake City (Sector V), Kolkata", icon: Building2, category: "IT Hub", district: "North 24 Parganas" },
  { name: "New Town (Action Area I), Kolkata", icon: Building2, category: "Area", district: "North 24 Parganas" },
  { name: "New Town (Action Area II), Kolkata", icon: Building2, category: "Area", district: "North 24 Parganas" },
  { name: "New Town (Action Area III), Kolkata", icon: Building2, category: "Area", district: "North 24 Parganas" },
  { name: "Rajarhat, Kolkata", icon: Building2, category: "Area", district: "North 24 Parganas" },
  { name: "Gariahat, Kolkata", icon: Building2, category: "Area", district: "Kolkata" },
  { name: "Behala, Kolkata", icon: Building2, category: "Area", district: "Kolkata" },
  { name: "Jadavpur, Kolkata", icon: Building2, category: "Area", district: "Kolkata" },
  { name: "Garia, Kolkata", icon: Building2, category: "Area", district: "Kolkata" },
  { name: "Tollygunge, Kolkata", icon: Building2, category: "Area", district: "Kolkata" },
  { name: "Ballygunge, Kolkata", icon: Building2, category: "Area", district: "Kolkata" },
  { name: "Alipore, Kolkata", icon: Building2, category: "Area", district: "Kolkata" },
  { name: "Bhowanipore, Kolkata", icon: Building2, category: "Area", district: "Kolkata" },
  { name: "Shyambazar, Kolkata", icon: Building2, category: "Area", district: "Kolkata" },
  { name: "Maniktala, Kolkata", icon: Building2, category: "Area", district: "Kolkata" },
  { name: "Ultadanga, Kolkata", icon: Building2, category: "Area", district: "Kolkata" },
  { name: "Kankurgachi, Kolkata", icon: Building2, category: "Area", district: "Kolkata" },
  { name: "Phool Bagan, Kolkata", icon: Building2, category: "Area", district: "Kolkata" },
  { name: "Lake Town, Kolkata", icon: Building2, category: "Area", district: "North 24 Parganas" },
  { name: "Bangur Avenue, Kolkata", icon: Building2, category: "Area", district: "North 24 Parganas" },
  { name: "Dum Dum, Kolkata", icon: Building2, category: "Area", district: "North 24 Parganas" },
  { name: "Nagerbazar, Kolkata", icon: Building2, category: "Area", district: "North 24 Parganas" },
  { name: "Jessore Road, Kolkata", icon: Building2, category: "Area", district: "North 24 Parganas" },
  { name: "VIP Road, Kolkata", icon: Building2, category: "Area", district: "North 24 Parganas" },
  { name: "EM Bypass, Kolkata", icon: Building2, category: "Area", district: "Kolkata" },
  { name: "Ruby, Kolkata", icon: Building2, category: "Area", district: "Kolkata" },
  { name: "Kasba, Kolkata", icon: Building2, category: "Area", district: "Kolkata" },
  { name: "Santoshpur, Kolkata", icon: Building2, category: "Area", district: "Kolkata" },
  { name: "Narendrapur, Kolkata", icon: Building2, category: "Area", district: "South 24 Parganas" },
  { name: "Sonarpur, Kolkata", icon: Building2, category: "Area", district: "South 24 Parganas" },
  { name: "Baruipur, South 24 Parganas", icon: Building2, category: "Town", district: "South 24 Parganas" },
  { name: "Thakurpukur, Kolkata", icon: Building2, category: "Area", district: "Kolkata" },
  { name: "Joka, Kolkata", icon: Building2, category: "Area", district: "South 24 Parganas" },
  { name: "Taratala, Kolkata", icon: Building2, category: "Area", district: "Kolkata" },
  { name: "Khidirpur, Kolkata", icon: Building2, category: "Area", district: "Kolkata" },
  { name: "Metiabruz, Kolkata", icon: Building2, category: "Area", district: "Kolkata" },
  { name: "Garden Reach, Kolkata", icon: Building2, category: "Area", district: "Kolkata" },
  { name: "Santragachi, Howrah", icon: Building2, category: "Area", district: "Howrah" },
  { name: "Shibpur, Howrah", icon: Building2, category: "Area", district: "Howrah" },
  { name: "Liluah, Howrah", icon: Building2, category: "Area", district: "Howrah" },
  { name: "Belur, Howrah", icon: Building2, category: "Area", district: "Howrah" },
  { name: "Bally, Howrah", icon: Building2, category: "Area", district: "Howrah" },
  
  // Bus Stands
  { name: "Esplanade Bus Stand, Kolkata", icon: Building2, category: "Bus Stand", district: "Kolkata" },
  { name: "Babughat Bus Stand, Kolkata", icon: Building2, category: "Bus Stand", district: "Kolkata" },
  { name: "Karunamoyee Bus Stand, Salt Lake", icon: Building2, category: "Bus Stand", district: "North 24 Parganas" },
  { name: "Ultadanga Bus Stand, Kolkata", icon: Building2, category: "Bus Stand", district: "Kolkata" },
  { name: "Dharmatala Bus Stand, Kolkata", icon: Building2, category: "Bus Stand", district: "Kolkata" },
  
  // Hospitals
  { name: "SSKM Hospital, Kolkata", icon: Building2, category: "Hospital", district: "Kolkata" },
  { name: "Medical College, Kolkata", icon: Building2, category: "Hospital", district: "Kolkata" },
  { name: "RG Kar Hospital, Kolkata", icon: Building2, category: "Hospital", district: "Kolkata" },
  { name: "NRS Hospital, Kolkata", icon: Building2, category: "Hospital", district: "Kolkata" },
  { name: "Apollo Hospital, Kolkata", icon: Building2, category: "Hospital", district: "Kolkata" },
  { name: "Fortis Hospital, Kolkata", icon: Building2, category: "Hospital", district: "Kolkata" },
  { name: "AMRI Hospital, Salt Lake", icon: Building2, category: "Hospital", district: "North 24 Parganas" },
  { name: "Peerless Hospital, Kolkata", icon: Building2, category: "Hospital", district: "Kolkata" },
  { name: "Chittaranjan Cancer Hospital, Kolkata", icon: Building2, category: "Hospital", district: "Kolkata" },
  
  // Shopping Malls
  { name: "South City Mall, Kolkata", icon: Building2, category: "Mall", district: "Kolkata" },
  { name: "Quest Mall, Kolkata", icon: Building2, category: "Mall", district: "Kolkata" },
  { name: "Acropolis Mall, Kolkata", icon: Building2, category: "Mall", district: "Kolkata" },
  { name: "Mani Square Mall, Kolkata", icon: Building2, category: "Mall", district: "Kolkata" },
  { name: "City Centre Salt Lake, Kolkata", icon: Building2, category: "Mall", district: "North 24 Parganas" },
  { name: "City Centre New Town, Kolkata", icon: Building2, category: "Mall", district: "North 24 Parganas" },
  { name: "Avani Riverside Mall, Howrah", icon: Building2, category: "Mall", district: "Howrah" },
  
  // Universities
  { name: "Jadavpur University, Kolkata", icon: Landmark, category: "University", district: "Kolkata" },
  { name: "Calcutta University, College Street", icon: Landmark, category: "University", district: "Kolkata" },
  { name: "Presidency University, Kolkata", icon: Landmark, category: "University", district: "Kolkata" },
  { name: "IIT Kharagpur", icon: Landmark, category: "University", district: "West Midnapore" },
  { name: "IIM Calcutta, Joka", icon: Landmark, category: "University", district: "South 24 Parganas" },
  { name: "IIEST Shibpur, Howrah", icon: Landmark, category: "University", district: "Howrah" },
  { name: "St. Xavier's College, Kolkata", icon: Landmark, category: "University", district: "Kolkata" },
  
  // ==================== NORTH 24 PARGANAS ====================
  { name: "Barasat, North 24 Parganas", icon: Building2, category: "City", district: "North 24 Parganas" },
  { name: "Barrackpore, North 24 Parganas", icon: Building2, category: "Town", district: "North 24 Parganas" },
  { name: "Madhyamgram, North 24 Parganas", icon: Building2, category: "Town", district: "North 24 Parganas" },
  { name: "Bongaon, North 24 Parganas", icon: Building2, category: "Town", district: "North 24 Parganas" },
  { name: "Basirhat, North 24 Parganas", icon: Building2, category: "Town", district: "North 24 Parganas" },
  { name: "Habra, North 24 Parganas", icon: Building2, category: "Town", district: "North 24 Parganas" },
  { name: "Ashoknagar, North 24 Parganas", icon: Building2, category: "Town", district: "North 24 Parganas" },
  { name: "Gobardanga, North 24 Parganas", icon: Building2, category: "Town", district: "North 24 Parganas" },
  { name: "Naihati, North 24 Parganas", icon: Building2, category: "Town", district: "North 24 Parganas" },
  { name: "Titagarh, North 24 Parganas", icon: Building2, category: "Town", district: "North 24 Parganas" },
  { name: "Khardaha, North 24 Parganas", icon: Building2, category: "Town", district: "North 24 Parganas" },
  { name: "Panihati, North 24 Parganas", icon: Building2, category: "Town", district: "North 24 Parganas" },
  { name: "Kamarhati, North 24 Parganas", icon: Building2, category: "Town", district: "North 24 Parganas" },
  { name: "Sodepur, North 24 Parganas", icon: Building2, category: "Town", district: "North 24 Parganas" },
  { name: "Bijpur, North 24 Parganas", icon: Building2, category: "Town", district: "North 24 Parganas" },
  { name: "Gaighata, North 24 Parganas", icon: Building2, category: "Town", district: "North 24 Parganas" },
  { name: "Hasnabad, North 24 Parganas", icon: Building2, category: "Town", district: "North 24 Parganas" },
  { name: "Hingalganj, North 24 Parganas", icon: Building2, category: "Town", district: "North 24 Parganas" },
  { name: "Minakhan, North 24 Parganas", icon: Building2, category: "Town", district: "North 24 Parganas" },
  { name: "Sandeshkhali, North 24 Parganas", icon: Building2, category: "Town", district: "North 24 Parganas" },
  
  // ==================== SOUTH 24 PARGANAS ====================
  { name: "Baruipur, South 24 Parganas", icon: Building2, category: "Town", district: "South 24 Parganas" },
  { name: "Canning, South 24 Parganas", icon: Building2, category: "Town", district: "South 24 Parganas" },
  { name: "Diamond Harbour, South 24 Parganas", icon: Ship, category: "Town", district: "South 24 Parganas" },
  { name: "Kakdwip, South 24 Parganas", icon: Building2, category: "Town", district: "South 24 Parganas" },
  { name: "Namkhana, South 24 Parganas", icon: Building2, category: "Town", district: "South 24 Parganas" },
  { name: "Sagar Island, South 24 Parganas", icon: Ship, category: "Island", district: "South 24 Parganas" },
  { name: "Gangasagar, South 24 Parganas", icon: Landmark, category: "Pilgrimage", district: "South 24 Parganas" },
  { name: "Bakkhali Beach, South 24 Parganas", icon: Ship, category: "Beach", district: "South 24 Parganas" },
  { name: "Frazerganj Beach, South 24 Parganas", icon: Ship, category: "Beach", district: "South 24 Parganas" },
  { name: "Henry Island, South 24 Parganas", icon: Ship, category: "Island", district: "South 24 Parganas" },
  { name: "Sundarbans, South 24 Parganas", icon: TreePine, category: "Wildlife", district: "South 24 Parganas" },
  { name: "Gosaba, South 24 Parganas", icon: Building2, category: "Town", district: "South 24 Parganas" },
  { name: "Basanti, South 24 Parganas", icon: Building2, category: "Town", district: "South 24 Parganas" },
  { name: "Kultali, South 24 Parganas", icon: Building2, category: "Town", district: "South 24 Parganas" },
  { name: "Mathurapur, South 24 Parganas", icon: Building2, category: "Town", district: "South 24 Parganas" },
  { name: "Joynagar, South 24 Parganas", icon: Building2, category: "Town", district: "South 24 Parganas" },
  { name: "Budge Budge, South 24 Parganas", icon: Building2, category: "Town", district: "South 24 Parganas" },
  { name: "Maheshtala, South 24 Parganas", icon: Building2, category: "Town", district: "South 24 Parganas" },
  { name: "Rajpur, South 24 Parganas", icon: Building2, category: "Town", district: "South 24 Parganas" },
  
  // ==================== HOWRAH ====================
  { name: "Howrah City, Howrah", icon: Building2, category: "City", district: "Howrah" },
  { name: "Uluberia, Howrah", icon: Building2, category: "Town", district: "Howrah" },
  { name: "Shyampur, Howrah", icon: Building2, category: "Town", district: "Howrah" },
  { name: "Bagnan, Howrah", icon: Building2, category: "Town", district: "Howrah" },
  { name: "Amta, Howrah", icon: Building2, category: "Town", district: "Howrah" },
  { name: "Udaynarayanpur, Howrah", icon: Building2, category: "Town", district: "Howrah" },
  { name: "Jagatballavpur, Howrah", icon: Building2, category: "Town", district: "Howrah" },
  { name: "Domjur, Howrah", icon: Building2, category: "Town", district: "Howrah" },
  { name: "Panchla, Howrah", icon: Building2, category: "Town", district: "Howrah" },
  
  // ==================== HOOGHLY ====================
  { name: "Chinsurah, Hooghly", icon: Building2, category: "City", district: "Hooghly" },
  { name: "Chandannagar, Hooghly", icon: Building2, category: "City", district: "Hooghly" },
  { name: "Serampore, Hooghly", icon: Building2, category: "City", district: "Hooghly" },
  { name: "Rishra, Hooghly", icon: Building2, category: "Town", district: "Hooghly" },
  { name: "Bandel, Hooghly", icon: Train, category: "Town", district: "Hooghly" },
  { name: "Bandel Church, Hooghly", icon: Landmark, category: "Church", district: "Hooghly" },
  { name: "Tarakeswar, Hooghly", icon: Landmark, category: "Temple", district: "Hooghly" },
  { name: "Arambagh, Hooghly", icon: Building2, category: "Town", district: "Hooghly" },
  { name: "Khanakul, Hooghly", icon: Building2, category: "Town", district: "Hooghly" },
  { name: "Pursurah, Hooghly", icon: Building2, category: "Town", district: "Hooghly" },
  { name: "Goghat, Hooghly", icon: Building2, category: "Town", district: "Hooghly" },
  { name: "Polba, Hooghly", icon: Building2, category: "Town", district: "Hooghly" },
  { name: "Singur, Hooghly", icon: Building2, category: "Town", district: "Hooghly" },
  { name: "Haripal, Hooghly", icon: Building2, category: "Town", district: "Hooghly" },
  { name: "Dhanekhali, Hooghly", icon: Building2, category: "Town", district: "Hooghly" },
  { name: "Tribeni, Hooghly", icon: Landmark, category: "Town", district: "Hooghly" },
  { name: "Mogra, Hooghly", icon: Building2, category: "Town", district: "Hooghly" },
  { name: "Uttarpara, Hooghly", icon: Building2, category: "Town", district: "Hooghly" },
  { name: "Dankuni, Hooghly", icon: Building2, category: "Town", district: "Hooghly" },
  
  // ==================== NADIA ====================
  { name: "Krishnanagar, Nadia", icon: Building2, category: "City", district: "Nadia" },
  { name: "Nabadwip, Nadia", icon: Landmark, category: "Pilgrimage", district: "Nadia" },
  { name: "Mayapur (ISKCON), Nadia", icon: Landmark, category: "Temple", district: "Nadia" },
  { name: "Ranaghat, Nadia", icon: Train, category: "Town", district: "Nadia" },
  { name: "Shantipur, Nadia", icon: Building2, category: "Town", district: "Nadia" },
  { name: "Chakdaha, Nadia", icon: Building2, category: "Town", district: "Nadia" },
  { name: "Kalyani, Nadia", icon: Building2, category: "Town", district: "Nadia" },
  { name: "Gayeshpur, Nadia", icon: Building2, category: "Town", district: "Nadia" },
  { name: "Tehatta, Nadia", icon: Building2, category: "Town", district: "Nadia" },
  { name: "Karimpur, Nadia", icon: Building2, category: "Town", district: "Nadia" },
  { name: "Nakashipara, Nadia", icon: Building2, category: "Town", district: "Nadia" },
  { name: "Chapra, Nadia", icon: Building2, category: "Town", district: "Nadia" },
  { name: "Bethuadahari, Nadia", icon: Building2, category: "Town", district: "Nadia" },
  { name: "Hanskhali, Nadia", icon: Building2, category: "Town", district: "Nadia" },
  
  // ==================== MURSHIDABAD ====================
  { name: "Berhampore, Murshidabad", icon: Building2, category: "City", district: "Murshidabad" },
  { name: "Murshidabad (Hazarduari), Murshidabad", icon: Landmark, category: "Heritage", district: "Murshidabad" },
  { name: "Lalbagh Court, Murshidabad", icon: Landmark, category: "Heritage", district: "Murshidabad" },
  { name: "Katra Mosque, Murshidabad", icon: Landmark, category: "Heritage", district: "Murshidabad" },
  { name: "Jiaganj, Murshidabad", icon: Building2, category: "Town", district: "Murshidabad" },
  { name: "Jangipur, Murshidabad", icon: Building2, category: "Town", district: "Murshidabad" },
  { name: "Farakka, Murshidabad", icon: Building2, category: "Town", district: "Murshidabad" },
  { name: "Suti, Murshidabad", icon: Building2, category: "Town", district: "Murshidabad" },
  { name: "Kandi, Murshidabad", icon: Building2, category: "Town", district: "Murshidabad" },
  { name: "Domkal, Murshidabad", icon: Building2, category: "Town", district: "Murshidabad" },
  { name: "Lalgola, Murshidabad", icon: Building2, category: "Town", district: "Murshidabad" },
  { name: "Raghunathganj, Murshidabad", icon: Building2, category: "Town", district: "Murshidabad" },
  { name: "Sagardighi, Murshidabad", icon: Building2, category: "Town", district: "Murshidabad" },
  { name: "Khargram, Murshidabad", icon: Building2, category: "Town", district: "Murshidabad" },
  { name: "Nabagram, Murshidabad", icon: Building2, category: "Town", district: "Murshidabad" },
  
  // ==================== BIRBHUM ====================
  { name: "Suri, Birbhum", icon: Building2, category: "City", district: "Birbhum" },
  { name: "Shantiniketan, Birbhum", icon: Landmark, category: "Heritage", district: "Birbhum" },
  { name: "Visva Bharati University, Shantiniketan", icon: Landmark, category: "University", district: "Birbhum" },
  { name: "Bolpur, Birbhum", icon: Train, category: "Town", district: "Birbhum" },
  { name: "Rampurhat, Birbhum", icon: Building2, category: "Town", district: "Birbhum" },
  { name: "Sainthia, Birbhum", icon: Building2, category: "Town", district: "Birbhum" },
  { name: "Dubrajpur, Birbhum", icon: Building2, category: "Town", district: "Birbhum" },
  { name: "Nalhati, Birbhum", icon: Building2, category: "Town", district: "Birbhum" },
  { name: "Mohammad Bazar, Birbhum", icon: Building2, category: "Town", district: "Birbhum" },
  { name: "Labhpur, Birbhum", icon: Building2, category: "Town", district: "Birbhum" },
  { name: "Nanoor, Birbhum", icon: Building2, category: "Town", district: "Birbhum" },
  { name: "Illambazar, Birbhum", icon: Building2, category: "Town", district: "Birbhum" },
  { name: "Murarai, Birbhum", icon: Building2, category: "Town", district: "Birbhum" },
  { name: "Tarapith, Birbhum", icon: Landmark, category: "Temple", district: "Birbhum" },
  { name: "Bakreshwar, Birbhum", icon: Landmark, category: "Temple", district: "Birbhum" },
  
  // ==================== BARDHAMAN (PURBA & PASCHIM) ====================
  { name: "Bardhaman City (Burdwan)", icon: Building2, category: "City", district: "Purba Bardhaman" },
  { name: "Bardhaman Station", icon: Train, category: "Railway Station", district: "Purba Bardhaman" },
  { name: "Durgapur, Paschim Bardhaman", icon: Building2, category: "City", district: "Paschim Bardhaman" },
  { name: "Asansol, Paschim Bardhaman", icon: Building2, category: "City", district: "Paschim Bardhaman" },
  { name: "Asansol Station", icon: Train, category: "Railway Station", district: "Paschim Bardhaman" },
  { name: "Raniganj, Paschim Bardhaman", icon: Building2, category: "Town", district: "Paschim Bardhaman" },
  { name: "Kulti, Paschim Bardhaman", icon: Building2, category: "Town", district: "Paschim Bardhaman" },
  { name: "Andal, Paschim Bardhaman", icon: Plane, category: "Airport", district: "Paschim Bardhaman" },
  { name: "Burnpur, Paschim Bardhaman", icon: Building2, category: "Town", district: "Paschim Bardhaman" },
  { name: "Jamuria, Paschim Bardhaman", icon: Building2, category: "Town", district: "Paschim Bardhaman" },
  { name: "Ondal, Paschim Bardhaman", icon: Building2, category: "Town", district: "Paschim Bardhaman" },
  { name: "Kalna, Purba Bardhaman", icon: Landmark, category: "Town", district: "Purba Bardhaman" },
  { name: "Katwa, Purba Bardhaman", icon: Building2, category: "Town", district: "Purba Bardhaman" },
  { name: "Memari, Purba Bardhaman", icon: Building2, category: "Town", district: "Purba Bardhaman" },
  { name: "Ausgram, Purba Bardhaman", icon: Building2, category: "Town", district: "Purba Bardhaman" },
  { name: "Galsi, Purba Bardhaman", icon: Building2, category: "Town", district: "Purba Bardhaman" },
  { name: "Monteswar, Purba Bardhaman", icon: Building2, category: "Town", district: "Purba Bardhaman" },
  { name: "Guskara, Purba Bardhaman", icon: Building2, category: "Town", district: "Purba Bardhaman" },
  
  // ==================== BANKURA ====================
  { name: "Bankura City, Bankura", icon: Building2, category: "City", district: "Bankura" },
  { name: "Bishnupur, Bankura", icon: Landmark, category: "Heritage", district: "Bankura" },
  { name: "Rasmancha, Bishnupur", icon: Landmark, category: "Heritage", district: "Bankura" },
  { name: "Terracotta Temples, Bishnupur", icon: Landmark, category: "Heritage", district: "Bankura" },
  { name: "Mukutmanipur, Bankura", icon: TreePine, category: "Tourist", district: "Bankura" },
  { name: "Susunia Hill, Bankura", icon: TreePine, category: "Tourist", district: "Bankura" },
  { name: "Jhilimili, Bankura", icon: TreePine, category: "Tourist", district: "Bankura" },
  { name: "Kotulpur, Bankura", icon: Building2, category: "Town", district: "Bankura" },
  { name: "Sonamukhi, Bankura", icon: Building2, category: "Town", district: "Bankura" },
  { name: "Onda, Bankura", icon: Building2, category: "Town", district: "Bankura" },
  { name: "Mejhia, Bankura", icon: Building2, category: "Town", district: "Bankura" },
  { name: "Khatra, Bankura", icon: Building2, category: "Town", district: "Bankura" },
  { name: "Ranibandh, Bankura", icon: Building2, category: "Town", district: "Bankura" },
  { name: "Sarenga, Bankura", icon: Building2, category: "Town", district: "Bankura" },
  
  // ==================== PURULIA ====================
  { name: "Purulia City, Purulia", icon: Building2, category: "City", district: "Purulia" },
  { name: "Ayodhya Hills, Purulia", icon: TreePine, category: "Hill", district: "Purulia" },
  { name: "Ajodhya Pahar, Purulia", icon: TreePine, category: "Hill", district: "Purulia" },
  { name: "Baranti Lake, Purulia", icon: TreePine, category: "Tourist", district: "Purulia" },
  { name: "Matha Forest, Purulia", icon: TreePine, category: "Nature", district: "Purulia" },
  { name: "Raghunathpur, Purulia", icon: Building2, category: "Town", district: "Purulia" },
  { name: "Adra, Purulia", icon: Train, category: "Town", district: "Purulia" },
  { name: "Jhalda, Purulia", icon: Building2, category: "Town", district: "Purulia" },
  { name: "Balarampur, Purulia", icon: Building2, category: "Town", district: "Purulia" },
  { name: "Manbazar, Purulia", icon: Building2, category: "Town", district: "Purulia" },
  { name: "Bundwan, Purulia", icon: Building2, category: "Town", district: "Purulia" },
  { name: "Arsha, Purulia", icon: Building2, category: "Town", district: "Purulia" },
  { name: "Bagmundi, Purulia", icon: Building2, category: "Town", district: "Purulia" },
  { name: "Kashipur, Purulia", icon: Building2, category: "Town", district: "Purulia" },
  { name: "Para, Purulia", icon: Building2, category: "Town", district: "Purulia" },
  { name: "Neturia, Purulia", icon: Building2, category: "Town", district: "Purulia" },
  
  // ==================== EAST MIDNAPORE ====================
  { name: "Tamluk, East Midnapore", icon: Building2, category: "City", district: "East Midnapore" },
  { name: "Haldia, East Midnapore", icon: Building2, category: "City", district: "East Midnapore" },
  { name: "Haldia Port, East Midnapore", icon: Ship, category: "Port", district: "East Midnapore" },
  { name: "Contai, East Midnapore", icon: Building2, category: "Town", district: "East Midnapore" },
  { name: "Digha Beach, East Midnapore", icon: Ship, category: "Beach", district: "East Midnapore" },
  { name: "New Digha, East Midnapore", icon: Ship, category: "Beach", district: "East Midnapore" },
  { name: "Old Digha, East Midnapore", icon: Ship, category: "Beach", district: "East Midnapore" },
  { name: "Mandarmani Beach, East Midnapore", icon: Ship, category: "Beach", district: "East Midnapore" },
  { name: "Tajpur Beach, East Midnapore", icon: Ship, category: "Beach", district: "East Midnapore" },
  { name: "Shankarpur Beach, East Midnapore", icon: Ship, category: "Beach", district: "East Midnapore" },
  { name: "Junput Beach, East Midnapore", icon: Ship, category: "Beach", district: "East Midnapore" },
  { name: "Mecheda, East Midnapore", icon: Building2, category: "Town", district: "East Midnapore" },
  { name: "Kolaghat, East Midnapore", icon: Building2, category: "Town", district: "East Midnapore" },
  { name: "Panskura, East Midnapore", icon: Building2, category: "Town", district: "East Midnapore" },
  { name: "Egra, East Midnapore", icon: Building2, category: "Town", district: "East Midnapore" },
  { name: "Khejuri, East Midnapore", icon: Building2, category: "Town", district: "East Midnapore" },
  { name: "Nandigram, East Midnapore", icon: Building2, category: "Town", district: "East Midnapore" },
  { name: "Sutahata, East Midnapore", icon: Building2, category: "Town", district: "East Midnapore" },
  { name: "Bhagwanpur, East Midnapore", icon: Building2, category: "Town", district: "East Midnapore" },
  { name: "Ramnagar, East Midnapore", icon: Building2, category: "Town", district: "East Midnapore" },
  { name: "Chandipur, East Midnapore", icon: Building2, category: "Town", district: "East Midnapore" },
  
  // ==================== WEST MIDNAPORE ====================
  { name: "Midnapore City, West Midnapore", icon: Building2, category: "City", district: "West Midnapore" },
  { name: "Kharagpur, West Midnapore", icon: Train, category: "City", district: "West Midnapore" },
  { name: "Kharagpur Railway Station", icon: Train, category: "Railway Station", district: "West Midnapore" },
  { name: "Ghatal, West Midnapore", icon: Building2, category: "Town", district: "West Midnapore" },
  { name: "Keshpur, West Midnapore", icon: Building2, category: "Town", district: "West Midnapore" },
  { name: "Garbeta, West Midnapore", icon: Building2, category: "Town", district: "West Midnapore" },
  { name: "Debra, West Midnapore", icon: Building2, category: "Town", district: "West Midnapore" },
  { name: "Pingla, West Midnapore", icon: Building2, category: "Town", district: "West Midnapore" },
  { name: "Dantan, West Midnapore", icon: Building2, category: "Town", district: "West Midnapore" },
  { name: "Mohanpur, West Midnapore", icon: Building2, category: "Town", district: "West Midnapore" },
  { name: "Narayangarh, West Midnapore", icon: Building2, category: "Town", district: "West Midnapore" },
  { name: "Sabang, West Midnapore", icon: Building2, category: "Town", district: "West Midnapore" },
  { name: "Salboni, West Midnapore", icon: Building2, category: "Town", district: "West Midnapore" },
  { name: "Belda, West Midnapore", icon: Building2, category: "Town", district: "West Midnapore" },
  
  // ==================== JHARGRAM ====================
  { name: "Jhargram, Jhargram", icon: Building2, category: "City", district: "Jhargram" },
  { name: "Jhargram Raj Palace", icon: Landmark, category: "Heritage", district: "Jhargram" },
  { name: "Belpahari, Jhargram", icon: TreePine, category: "Nature", district: "Jhargram" },
  { name: "Kankrajhore, Jhargram", icon: TreePine, category: "Nature", district: "Jhargram" },
  { name: "Gopiballavpur, Jhargram", icon: Building2, category: "Town", district: "Jhargram" },
  { name: "Nayagram, Jhargram", icon: Building2, category: "Town", district: "Jhargram" },
  { name: "Binpur, Jhargram", icon: Building2, category: "Town", district: "Jhargram" },
  { name: "Jamboni, Jhargram", icon: Building2, category: "Town", district: "Jhargram" },
  { name: "Lalgarh, Jhargram", icon: Building2, category: "Town", district: "Jhargram" },
  { name: "Sankrail, Jhargram", icon: Building2, category: "Town", district: "Jhargram" },
  
  // ==================== MALDA ====================
  { name: "Malda City (English Bazar)", icon: Building2, category: "City", district: "Malda" },
  { name: "Malda Station", icon: Train, category: "Railway Station", district: "Malda" },
  { name: "Gaur, Malda", icon: Landmark, category: "Heritage", district: "Malda" },
  { name: "Pandua, Malda", icon: Landmark, category: "Heritage", district: "Malda" },
  { name: "Adina Mosque, Malda", icon: Landmark, category: "Heritage", district: "Malda" },
  { name: "Old Malda, Malda", icon: Building2, category: "Town", district: "Malda" },
  { name: "Kaliachak, Malda", icon: Building2, category: "Town", district: "Malda" },
  { name: "Harischandrapur, Malda", icon: Building2, category: "Town", district: "Malda" },
  { name: "Chanchal, Malda", icon: Building2, category: "Town", district: "Malda" },
  { name: "Ratua, Malda", icon: Building2, category: "Town", district: "Malda" },
  { name: "Habibpur, Malda", icon: Building2, category: "Town", district: "Malda" },
  { name: "Gazole, Malda", icon: Building2, category: "Town", district: "Malda" },
  { name: "Manikchak, Malda", icon: Building2, category: "Town", district: "Malda" },
  { name: "Bamongola, Malda", icon: Building2, category: "Town", district: "Malda" },
  
  // ==================== UTTAR DINAJPUR ====================
  { name: "Raiganj, Uttar Dinajpur", icon: Building2, category: "City", district: "Uttar Dinajpur" },
  { name: "Raiganj Wildlife Sanctuary", icon: TreePine, category: "Wildlife", district: "Uttar Dinajpur" },
  { name: "Islampur, Uttar Dinajpur", icon: Building2, category: "Town", district: "Uttar Dinajpur" },
  { name: "Dalkhola, Uttar Dinajpur", icon: Building2, category: "Town", district: "Uttar Dinajpur" },
  { name: "Kaliaganj, Uttar Dinajpur", icon: Building2, category: "Town", district: "Uttar Dinajpur" },
  { name: "Hemtabad, Uttar Dinajpur", icon: Building2, category: "Town", district: "Uttar Dinajpur" },
  { name: "Itahar, Uttar Dinajpur", icon: Building2, category: "Town", district: "Uttar Dinajpur" },
  { name: "Karandighi, Uttar Dinajpur", icon: Building2, category: "Town", district: "Uttar Dinajpur" },
  { name: "Chopra, Uttar Dinajpur", icon: Building2, category: "Town", district: "Uttar Dinajpur" },
  { name: "Goalpokhar, Uttar Dinajpur", icon: Building2, category: "Town", district: "Uttar Dinajpur" },
  
  // ==================== DAKSHIN DINAJPUR ====================
  { name: "Balurghat, Dakshin Dinajpur", icon: Building2, category: "City", district: "Dakshin Dinajpur" },
  { name: "Gangarampur, Dakshin Dinajpur", icon: Building2, category: "Town", district: "Dakshin Dinajpur" },
  { name: "Buniadpur, Dakshin Dinajpur", icon: Building2, category: "Town", district: "Dakshin Dinajpur" },
  { name: "Kumarganj, Dakshin Dinajpur", icon: Building2, category: "Town", district: "Dakshin Dinajpur" },
  { name: "Tapan, Dakshin Dinajpur", icon: Building2, category: "Town", district: "Dakshin Dinajpur" },
  { name: "Kushmandi, Dakshin Dinajpur", icon: Building2, category: "Town", district: "Dakshin Dinajpur" },
  { name: "Hili, Dakshin Dinajpur", icon: Building2, category: "Town", district: "Dakshin Dinajpur" },
  { name: "Bansihari, Dakshin Dinajpur", icon: Building2, category: "Town", district: "Dakshin Dinajpur" },
  
  // ==================== DARJEELING ====================
  { name: "Darjeeling Town, Darjeeling", icon: TreePine, category: "Hill Station", district: "Darjeeling" },
  { name: "Darjeeling Railway Station (DHR)", icon: Train, category: "Railway Station", district: "Darjeeling" },
  { name: "Tiger Hill, Darjeeling", icon: TreePine, category: "View Point", district: "Darjeeling" },
  { name: "Batasia Loop, Darjeeling", icon: Landmark, category: "Landmark", district: "Darjeeling" },
  { name: "Mall Road, Darjeeling", icon: Building2, category: "Area", district: "Darjeeling" },
  { name: "Chowrasta, Darjeeling", icon: Building2, category: "Area", district: "Darjeeling" },
  { name: "Ghum, Darjeeling", icon: Train, category: "Town", district: "Darjeeling" },
  { name: "Himalayan Mountaineering Institute", icon: Landmark, category: "Museum", district: "Darjeeling" },
  { name: "Padmaja Naidu Zoo, Darjeeling", icon: TreePine, category: "Zoo", district: "Darjeeling" },
  { name: "Japanese Temple, Darjeeling", icon: Landmark, category: "Temple", district: "Darjeeling" },
  { name: "Peace Pagoda, Darjeeling", icon: Landmark, category: "Temple", district: "Darjeeling" },
  { name: "Rock Garden, Darjeeling", icon: TreePine, category: "Tourist", district: "Darjeeling" },
  { name: "Happy Valley Tea Estate", icon: TreePine, category: "Tea Garden", district: "Darjeeling" },
  { name: "Mirik, Darjeeling", icon: TreePine, category: "Hill Station", district: "Darjeeling" },
  { name: "Mirik Lake, Darjeeling", icon: TreePine, category: "Lake", district: "Darjeeling" },
  { name: "Kurseong, Darjeeling", icon: TreePine, category: "Hill Station", district: "Darjeeling" },
  { name: "Kurseong Station", icon: Train, category: "Railway Station", district: "Darjeeling" },
  { name: "Dow Hill, Kurseong", icon: TreePine, category: "View Point", district: "Darjeeling" },
  { name: "Eagle's Crag, Kurseong", icon: TreePine, category: "View Point", district: "Darjeeling" },
  { name: "Sukhiapokhri, Darjeeling", icon: Building2, category: "Town", district: "Darjeeling" },
  { name: "Sonada, Darjeeling", icon: Building2, category: "Town", district: "Darjeeling" },
  { name: "Jorebunglow, Darjeeling", icon: Building2, category: "Town", district: "Darjeeling" },
  { name: "Sukna, Darjeeling", icon: Building2, category: "Town", district: "Darjeeling" },
  
  // ==================== KALIMPONG ====================
  { name: "Kalimpong Town, Kalimpong", icon: TreePine, category: "Hill Station", district: "Kalimpong" },
  { name: "Deolo Hill, Kalimpong", icon: TreePine, category: "View Point", district: "Kalimpong" },
  { name: "Durpin Monastery, Kalimpong", icon: Landmark, category: "Monastery", district: "Kalimpong" },
  { name: "Thongsa Gumpha, Kalimpong", icon: Landmark, category: "Monastery", district: "Kalimpong" },
  { name: "Cactus Nursery, Kalimpong", icon: TreePine, category: "Nursery", district: "Kalimpong" },
  { name: "Lava, Kalimpong", icon: TreePine, category: "Hill Station", district: "Kalimpong" },
  { name: "Lolegaon, Kalimpong", icon: TreePine, category: "Hill Station", district: "Kalimpong" },
  { name: "Rishyap, Kalimpong", icon: TreePine, category: "Hill Station", district: "Kalimpong" },
  { name: "Pedong, Kalimpong", icon: Building2, category: "Town", district: "Kalimpong" },
  { name: "Algarah, Kalimpong", icon: Building2, category: "Town", district: "Kalimpong" },
  { name: "Gorubathan, Kalimpong", icon: Building2, category: "Town", district: "Kalimpong" },
  
  // ==================== JALPAIGURI ====================
  { name: "Jalpaiguri City, Jalpaiguri", icon: Building2, category: "City", district: "Jalpaiguri" },
  { name: "Jalpaiguri Station", icon: Train, category: "Railway Station", district: "Jalpaiguri" },
  { name: "Mainaguri, Jalpaiguri", icon: Building2, category: "Town", district: "Jalpaiguri" },
  { name: "Mal, Jalpaiguri", icon: Building2, category: "Town", district: "Jalpaiguri" },
  { name: "Nagrakata, Jalpaiguri", icon: Building2, category: "Town", district: "Jalpaiguri" },
  { name: "Matelli, Jalpaiguri", icon: Building2, category: "Town", district: "Jalpaiguri" },
  { name: "Dhupguri, Jalpaiguri", icon: Building2, category: "Town", district: "Jalpaiguri" },
  { name: "Malbazar, Jalpaiguri", icon: Building2, category: "Town", district: "Jalpaiguri" },
  { name: "Chalsa, Jalpaiguri", icon: Building2, category: "Town", district: "Jalpaiguri" },
  { name: "Gorumara National Park", icon: TreePine, category: "Wildlife", district: "Jalpaiguri" },
  { name: "Chapramari Wildlife Sanctuary", icon: TreePine, category: "Wildlife", district: "Jalpaiguri" },
  { name: "Buxa Tiger Reserve", icon: TreePine, category: "Wildlife", district: "Jalpaiguri" },
  { name: "Rajabhatkhawa, Jalpaiguri", icon: Building2, category: "Town", district: "Jalpaiguri" },
  
  // ==================== ALIPURDUAR ====================
  { name: "Alipurduar City, Alipurduar", icon: Building2, category: "City", district: "Alipurduar" },
  { name: "Alipurduar Junction Station", icon: Train, category: "Railway Station", district: "Alipurduar" },
  { name: "Falakata, Alipurduar", icon: Building2, category: "Town", district: "Alipurduar" },
  { name: "Madarihat, Alipurduar", icon: Building2, category: "Town", district: "Alipurduar" },
  { name: "Samuktala, Alipurduar", icon: Building2, category: "Town", district: "Alipurduar" },
  { name: "Kumargram, Alipurduar", icon: Building2, category: "Town", district: "Alipurduar" },
  { name: "Birpara, Alipurduar", icon: Building2, category: "Town", district: "Alipurduar" },
  { name: "Kalchini, Alipurduar", icon: Building2, category: "Town", district: "Alipurduar" },
  { name: "Jaldapara National Park", icon: TreePine, category: "Wildlife", district: "Alipurduar" },
  { name: "Hollong, Jaldapara", icon: TreePine, category: "Tourist", district: "Alipurduar" },
  { name: "Chilapata Forest, Alipurduar", icon: TreePine, category: "Nature", district: "Alipurduar" },
  { name: "Buxa Fort, Alipurduar", icon: Landmark, category: "Heritage", district: "Alipurduar" },
  { name: "Jayanti, Alipurduar", icon: TreePine, category: "Nature", district: "Alipurduar" },
  { name: "Phuentsholing (Bhutan Border)", icon: Building2, category: "Border", district: "Alipurduar" },
  
  // ==================== COOCH BEHAR ====================
  { name: "Cooch Behar City, Cooch Behar", icon: Building2, category: "City", district: "Cooch Behar" },
  { name: "Cooch Behar Palace (Rajbari)", icon: Landmark, category: "Heritage", district: "Cooch Behar" },
  { name: "Madan Mohan Temple, Cooch Behar", icon: Landmark, category: "Temple", district: "Cooch Behar" },
  { name: "Sagar Dighi, Cooch Behar", icon: TreePine, category: "Lake", district: "Cooch Behar" },
  { name: "Rasik Bil, Cooch Behar", icon: TreePine, category: "Wildlife", district: "Cooch Behar" },
  { name: "New Cooch Behar Station", icon: Train, category: "Railway Station", district: "Cooch Behar" },
  { name: "Tufanganj, Cooch Behar", icon: Building2, category: "Town", district: "Cooch Behar" },
  { name: "Mathabhanga, Cooch Behar", icon: Building2, category: "Town", district: "Cooch Behar" },
  { name: "Dinhata, Cooch Behar", icon: Building2, category: "Town", district: "Cooch Behar" },
  { name: "Sitalkuchi, Cooch Behar", icon: Building2, category: "Town", district: "Cooch Behar" },
  { name: "Mekhliganj, Cooch Behar", icon: Building2, category: "Town", district: "Cooch Behar" },
  { name: "Haldibari, Cooch Behar", icon: Building2, category: "Town", district: "Cooch Behar" },
  { name: "Sitai, Cooch Behar", icon: Building2, category: "Town", district: "Cooch Behar" },
  
  // ==================== SILIGURI & SURROUNDING ====================
  { name: "Siliguri City, Darjeeling", icon: Building2, category: "City", district: "Darjeeling" },
  { name: "Siliguri Junction Station", icon: Train, category: "Railway Station", district: "Darjeeling" },
  { name: "New Jalpaiguri Station (NJP)", icon: Train, category: "Railway Station", district: "Jalpaiguri" },
  { name: "Bagdogra Airport, Siliguri", icon: Plane, category: "Airport", district: "Darjeeling" },
  { name: "Tenzing Norgay Bus Stand, Siliguri", icon: Building2, category: "Bus Stand", district: "Darjeeling" },
  { name: "Hill Cart Road, Siliguri", icon: Building2, category: "Area", district: "Darjeeling" },
  { name: "Sevoke Road, Siliguri", icon: Building2, category: "Area", district: "Darjeeling" },
  { name: "Matigara, Siliguri", icon: Building2, category: "Area", district: "Darjeeling" },
  { name: "Pradhan Nagar, Siliguri", icon: Building2, category: "Area", district: "Darjeeling" },
  { name: "Salugara, Siliguri", icon: Building2, category: "Area", district: "Darjeeling" },
  { name: "Salugara Monastery, Siliguri", icon: Landmark, category: "Monastery", district: "Darjeeling" },
  { name: "Kharibari, Siliguri", icon: Building2, category: "Town", district: "Darjeeling" },
  { name: "Naxalbari, Siliguri", icon: Building2, category: "Town", district: "Darjeeling" },
  { name: "Phansidewa, Siliguri", icon: Building2, category: "Town", district: "Darjeeling" },
  { name: "Mahananda Wildlife Sanctuary", icon: TreePine, category: "Wildlife", district: "Darjeeling" },
  { name: "Coronation Bridge (Sevoke)", icon: Landmark, category: "Landmark", district: "Darjeeling" },
  { name: "Teesta Bazaar, Siliguri", icon: Building2, category: "Area", district: "Darjeeling" },
  
  // ==================== DOOARS REGION ====================
  { name: "Dooars, West Bengal", icon: TreePine, category: "Nature", district: "Jalpaiguri" },
  { name: "Lataguri, Dooars", icon: TreePine, category: "Tourist", district: "Jalpaiguri" },
  { name: "Murti, Dooars", icon: TreePine, category: "Tourist", district: "Jalpaiguri" },
  { name: "Samsing, Dooars", icon: TreePine, category: "Tourist", district: "Kalimpong" },
  { name: "Suntalekhola, Dooars", icon: TreePine, category: "Tourist", district: "Kalimpong" },
  { name: "Bindu, Dooars", icon: TreePine, category: "Tourist", district: "Kalimpong" },
  { name: "Rocky Island, Dooars", icon: TreePine, category: "Tourist", district: "Kalimpong" },
  { name: "Jhalong, Dooars", icon: TreePine, category: "Tourist", district: "Kalimpong" },
  { name: "Mendabari, Dooars", icon: TreePine, category: "Tourist", district: "Jalpaiguri" },
  { name: "Paren, Dooars", icon: TreePine, category: "Tourist", district: "Jalpaiguri" },
  { name: "Totopara, Dooars", icon: Building2, category: "Village", district: "Alipurduar" },
  
  // ==================== NEARBY CITIES (OUTSIDE WB) ====================
  { name: "Patna, Bihar", icon: Building2, category: "City", district: "Bihar" },
  { name: "Ranchi, Jharkhand", icon: Building2, category: "City", district: "Jharkhand" },
  { name: "Jamshedpur, Jharkhand", icon: Building2, category: "City", district: "Jharkhand" },
  { name: "Dhanbad, Jharkhand", icon: Building2, category: "City", district: "Jharkhand" },
  { name: "Bhubaneswar, Odisha", icon: Building2, category: "City", district: "Odisha" },
  { name: "Puri, Odisha", icon: Landmark, category: "Pilgrimage", district: "Odisha" },
  { name: "Guwahati, Assam", icon: Building2, category: "City", district: "Assam" },
  { name: "Shillong, Meghalaya", icon: TreePine, category: "Hill Station", district: "Meghalaya" },
  { name: "Gangtok, Sikkim", icon: TreePine, category: "Hill Station", district: "Sikkim" },
  { name: "Varanasi, Uttar Pradesh", icon: Landmark, category: "Pilgrimage", district: "Uttar Pradesh" },
  { name: "Delhi", icon: Building2, category: "City", district: "Delhi" },
  { name: "Mumbai", icon: Building2, category: "City", district: "Maharashtra" },
  { name: "Bangalore", icon: Building2, category: "City", district: "Karnataka" },
  { name: "Chennai", icon: Building2, category: "City", district: "Tamil Nadu" },
  { name: "Hyderabad", icon: Building2, category: "City", district: "Telangana" },
];
