import { Building2, Landmark, TreePine, Plane, Train, Ship } from "lucide-react";

export interface Location {
  name: string;
  icon: typeof Building2;
  category: string;
  district: string;
  aliases?: string[];
}

export const westBengalLocations: Location[] = [
  // ==================== KOLKATA ====================
  { name: "Howrah Station, Kolkata", icon: Train, category: "Railway Station", district: "Howrah", aliases: ["howrah junction", "hwh", "main station", "railway", "train"] },
  { name: "Sealdah Station, Kolkata", icon: Train, category: "Railway Station", district: "Kolkata", aliases: ["sdah", "sealdah junction", "railway", "train", "local train"] },
  { name: "Kolkata Station (Chitpur)", icon: Train, category: "Railway Station", district: "Kolkata", aliases: ["koaa", "chitpur station", "railway"] },
  { name: "Santragachi Station, Howrah", icon: Train, category: "Railway Station", district: "Howrah", aliases: ["src", "railway", "junction"] },
  { name: "Shalimar Station, Howrah", icon: Train, category: "Railway Station", district: "Howrah", aliases: ["shm", "railway"] },
  { name: "Netaji Subhas Chandra Bose Airport, Kolkata", icon: Plane, category: "Airport", district: "North 24 Parganas", aliases: ["kolkata airport", "dum dum airport", "ccu", "nscbi", "international airport", "domestic airport", "flight", "plane", "fly"] },
  { name: "Victoria Memorial, Kolkata", icon: Landmark, category: "Landmark", district: "Kolkata", aliases: ["victoria", "white palace", "museum", "heritage", "tourist spot"] },
  { name: "Dakshineswar Kali Temple, Kolkata", icon: Landmark, category: "Temple", district: "North 24 Parganas", aliases: ["dakshineswar", "kali mandir", "ramakrishna", "temple", "religious"] },
  { name: "Kalighat Temple, Kolkata", icon: Landmark, category: "Temple", district: "Kolkata", aliases: ["kalighat", "kali temple", "shakti peeth", "religious"] },
  { name: "Belur Math, Howrah", icon: Landmark, category: "Temple", district: "Howrah", aliases: ["belur", "ramakrishna mission", "swami vivekananda", "monastery", "religious"] },
  { name: "Indian Museum, Kolkata", icon: Landmark, category: "Museum", district: "Kolkata", aliases: ["museum", "jadughar", "artifact", "history"] },
  { name: "Science City, Kolkata", icon: Building2, category: "Landmark", district: "Kolkata", aliases: ["science museum", "science centre", "planetarium", "kids", "family"] },
  { name: "Eco Park, New Town", icon: TreePine, category: "Park", district: "North 24 Parganas", aliases: ["eco tourism park", "rajarhat", "picnic", "boating", "family"] },
  { name: "Nicco Park, Salt Lake", icon: TreePine, category: "Park", district: "North 24 Parganas", aliases: ["amusement park", "theme park", "rides", "kids", "family"] },
  { name: "Birla Planetarium, Kolkata", icon: Landmark, category: "Landmark", district: "Kolkata", aliases: ["planetarium", "space", "astronomy", "stars"] },
  { name: "Eden Gardens, Kolkata", icon: Landmark, category: "Stadium", district: "Kolkata", aliases: ["cricket stadium", "ipl", "match", "sports", "cab"] },
  { name: "Salt Lake Stadium, Kolkata", icon: Landmark, category: "Stadium", district: "North 24 Parganas", aliases: ["vivekananda stadium", "football", "yuba bharati", "sports"] },
  { name: "Netaji Indoor Stadium, Kolkata", icon: Landmark, category: "Stadium", district: "Kolkata", aliases: ["indoor games", "badminton", "sports"] },
  { name: "Princep Ghat, Kolkata", icon: Landmark, category: "Landmark", district: "Kolkata", aliases: ["prinsep", "ganga ghat", "riverside", "boating", "evening"] },
  { name: "Millennium Park, Kolkata", icon: TreePine, category: "Park", district: "Kolkata", aliases: ["riverside park", "hooghly", "evening walk"] },
  { name: "Rabindra Sadan, Kolkata", icon: Landmark, category: "Landmark", district: "Kolkata", aliases: ["auditorium", "cultural", "theatre", "performance"] },
  { name: "Nandan, Kolkata", icon: Landmark, category: "Landmark", district: "Kolkata", aliases: ["film center", "movie", "cinema", "kiff"] },
  { name: "Academy of Fine Arts, Kolkata", icon: Landmark, category: "Landmark", district: "Kolkata", aliases: ["art gallery", "painting", "exhibition"] },
  
  // Kolkata Areas
  { name: "Park Street, Kolkata", icon: Building2, category: "Area", district: "Kolkata", aliases: ["food street", "restaurants", "nightlife", "party", "pubs", "bars"] },
  { name: "Esplanade, Kolkata", icon: Building2, category: "Area", district: "Kolkata", aliases: ["shopping", "metro", "central", "dharmatala"] },
  { name: "Salt Lake City (Sector I), Kolkata", icon: Building2, category: "Area", district: "North 24 Parganas", aliases: ["bidhannagar", "sector 1"] },
  { name: "Salt Lake City (Sector II), Kolkata", icon: Building2, category: "Area", district: "North 24 Parganas", aliases: ["bidhannagar", "sector 2"] },
  { name: "Salt Lake City (Sector III), Kolkata", icon: Building2, category: "Area", district: "North 24 Parganas", aliases: ["bidhannagar", "sector 3"] },
  { name: "Salt Lake City (Sector V), Kolkata", icon: Building2, category: "IT Hub", district: "North 24 Parganas", aliases: ["bidhannagar", "sector 5", "it park", "tech park", "office", "tcs", "wipro", "cognizant"] },
  { name: "New Town (Action Area I), Kolkata", icon: Building2, category: "Area", district: "North 24 Parganas", aliases: ["rajarhat", "aa1"] },
  { name: "New Town (Action Area II), Kolkata", icon: Building2, category: "Area", district: "North 24 Parganas", aliases: ["rajarhat", "aa2", "biswa bangla gate"] },
  { name: "New Town (Action Area III), Kolkata", icon: Building2, category: "Area", district: "North 24 Parganas", aliases: ["rajarhat", "aa3"] },
  { name: "Rajarhat, Kolkata", icon: Building2, category: "Area", district: "North 24 Parganas", aliases: ["new town", "it hub"] },
  { name: "Gariahat, Kolkata", icon: Building2, category: "Area", district: "Kolkata", aliases: ["gariahaat", "shopping", "market", "south kolkata"] },
  { name: "Behala, Kolkata", icon: Building2, category: "Area", district: "Kolkata", aliases: ["south kolkata", "residential"] },
  { name: "Jadavpur, Kolkata", icon: Building2, category: "Area", district: "Kolkata", aliases: ["ju", "south kolkata"] },
  { name: "Garia, Kolkata", icon: Building2, category: "Area", district: "Kolkata", aliases: ["metro", "south kolkata"] },
  { name: "Tollygunge, Kolkata", icon: Building2, category: "Area", district: "Kolkata", aliases: ["tolly", "metro", "tollywood", "film studios"] },
  { name: "Ballygunge, Kolkata", icon: Building2, category: "Area", district: "Kolkata", aliases: ["ballygunje", "posh area", "south kolkata"] },
  { name: "Alipore, Kolkata", icon: Building2, category: "Area", district: "Kolkata", aliases: ["zoo", "national library", "posh area"] },
  { name: "Bhowanipore, Kolkata", icon: Building2, category: "Area", district: "Kolkata", aliases: ["bhawanipore", "south kolkata"] },
  { name: "Shyambazar, Kolkata", icon: Building2, category: "Area", district: "Kolkata", aliases: ["north kolkata", "5 point crossing"] },
  { name: "Maniktala, Kolkata", icon: Building2, category: "Area", district: "Kolkata", aliases: ["north kolkata"] },
  { name: "Ultadanga, Kolkata", icon: Building2, category: "Area", district: "Kolkata", aliases: ["flyover", "central kolkata"] },
  { name: "Kankurgachi, Kolkata", icon: Building2, category: "Area", district: "Kolkata", aliases: ["central kolkata"] },
  { name: "Phool Bagan, Kolkata", icon: Building2, category: "Area", district: "Kolkata", aliases: ["central kolkata"] },
  { name: "Lake Town, Kolkata", icon: Building2, category: "Area", district: "North 24 Parganas", aliases: ["laketown", "residential"] },
  { name: "Bangur Avenue, Kolkata", icon: Building2, category: "Area", district: "North 24 Parganas", aliases: ["bangur", "residential"] },
  { name: "Dum Dum, Kolkata", icon: Building2, category: "Area", district: "North 24 Parganas", aliases: ["dumdum", "airport area", "north kolkata"] },
  { name: "Nagerbazar, Kolkata", icon: Building2, category: "Area", district: "North 24 Parganas", aliases: ["nager bazar", "dum dum"] },
  { name: "Jessore Road, Kolkata", icon: Building2, category: "Area", district: "North 24 Parganas", aliases: ["jessop road", "airport road"] },
  { name: "VIP Road, Kolkata", icon: Building2, category: "Area", district: "North 24 Parganas", aliases: ["airport road", "kestopur"] },
  { name: "EM Bypass, Kolkata", icon: Building2, category: "Area", district: "Kolkata", aliases: ["bypass", "eastern metropolitan"] },
  { name: "Ruby, Kolkata", icon: Building2, category: "Area", district: "Kolkata", aliases: ["ruby hospital", "anandapur", "em bypass"] },
  { name: "Kasba, Kolkata", icon: Building2, category: "Area", district: "Kolkata", aliases: ["south kolkata"] },
  { name: "Santoshpur, Kolkata", icon: Building2, category: "Area", district: "Kolkata", aliases: ["south kolkata"] },
  { name: "Narendrapur, Kolkata", icon: Building2, category: "Area", district: "South 24 Parganas", aliases: ["ramakrishna mission", "south kolkata"] },
  { name: "Sonarpur, Kolkata", icon: Building2, category: "Area", district: "South 24 Parganas", aliases: ["south kolkata"] },
  { name: "Baruipur, South 24 Parganas", icon: Building2, category: "Town", district: "South 24 Parganas", aliases: ["subdivision", "south"] },
  { name: "Thakurpukur, Kolkata", icon: Building2, category: "Area", district: "Kolkata", aliases: ["south kolkata", "cancer hospital"] },
  { name: "Joka, Kolkata", icon: Building2, category: "Area", district: "South 24 Parganas", aliases: ["iim", "metro", "south kolkata"] },
  { name: "Taratala, Kolkata", icon: Building2, category: "Area", district: "Kolkata", aliases: ["south kolkata"] },
  { name: "Khidirpur, Kolkata", icon: Building2, category: "Area", district: "Kolkata", aliases: ["kidderpore", "port", "dock"] },
  { name: "Metiabruz, Kolkata", icon: Building2, category: "Area", district: "Kolkata", aliases: ["metiaburuz", "south kolkata"] },
  { name: "Garden Reach, Kolkata", icon: Building2, category: "Area", district: "Kolkata", aliases: ["grse", "shipyard"] },
  { name: "Santragachi, Howrah", icon: Building2, category: "Area", district: "Howrah", aliases: ["jheel", "lake", "birds"] },
  { name: "Shibpur, Howrah", icon: Building2, category: "Area", district: "Howrah", aliases: ["botanical garden", "iiest", "be college"] },
  { name: "Liluah, Howrah", icon: Building2, category: "Area", district: "Howrah", aliases: ["railway workshop"] },
  { name: "Belur, Howrah", icon: Building2, category: "Area", district: "Howrah", aliases: ["belur math"] },
  { name: "Bally, Howrah", icon: Building2, category: "Area", district: "Howrah", aliases: ["balee"] },
  
  // Bus Stands
  { name: "Esplanade Bus Stand, Kolkata", icon: Building2, category: "Bus Stand", district: "Kolkata", aliases: ["bus terminus", "bus terminal", "bus station", "volvo", "ac bus"] },
  { name: "Babughat Bus Stand, Kolkata", icon: Building2, category: "Bus Stand", district: "Kolkata", aliases: ["bus terminus", "bus terminal", "ghat"] },
  { name: "Karunamoyee Bus Stand, Salt Lake", icon: Building2, category: "Bus Stand", district: "North 24 Parganas", aliases: ["bus terminus", "salt lake bus"] },
  { name: "Ultadanga Bus Stand, Kolkata", icon: Building2, category: "Bus Stand", district: "Kolkata", aliases: ["bus terminus", "north bengal bus"] },
  { name: "Dharmatala Bus Stand, Kolkata", icon: Building2, category: "Bus Stand", district: "Kolkata", aliases: ["bus terminus", "central bus"] },
  
  // Hospitals
  { name: "SSKM Hospital, Kolkata", icon: Building2, category: "Hospital", district: "Kolkata", aliases: ["pg hospital", "peerless", "government hospital", "medical", "doctor", "emergency"] },
  { name: "Medical College, Kolkata", icon: Building2, category: "Hospital", district: "Kolkata", aliases: ["calcutta medical", "government hospital", "doctor", "emergency"] },
  { name: "RG Kar Hospital, Kolkata", icon: Building2, category: "Hospital", district: "Kolkata", aliases: ["rg kar medical college", "government hospital", "doctor"] },
  { name: "NRS Hospital, Kolkata", icon: Building2, category: "Hospital", district: "Kolkata", aliases: ["nil ratan sircar", "government hospital", "doctor"] },
  { name: "Apollo Hospital, Kolkata", icon: Building2, category: "Hospital", district: "Kolkata", aliases: ["private hospital", "doctor", "emergency", "multispeciality"] },
  { name: "Fortis Hospital, Kolkata", icon: Building2, category: "Hospital", district: "Kolkata", aliases: ["private hospital", "doctor", "emergency", "multispeciality"] },
  { name: "AMRI Hospital, Salt Lake", icon: Building2, category: "Hospital", district: "North 24 Parganas", aliases: ["private hospital", "doctor", "emergency"] },
  { name: "Peerless Hospital, Kolkata", icon: Building2, category: "Hospital", district: "Kolkata", aliases: ["private hospital", "doctor"] },
  { name: "Chittaranjan Cancer Hospital, Kolkata", icon: Building2, category: "Hospital", district: "Kolkata", aliases: ["cancer treatment", "oncology"] },
  
  // Shopping Malls
  { name: "South City Mall, Kolkata", icon: Building2, category: "Mall", district: "Kolkata", aliases: ["shopping mall", "pvr", "inox", "movies", "shopping", "multiplex"] },
  { name: "Quest Mall, Kolkata", icon: Building2, category: "Mall", district: "Kolkata", aliases: ["shopping mall", "premium", "luxury", "brands", "multiplex"] },
  { name: "Acropolis Mall, Kolkata", icon: Building2, category: "Mall", district: "Kolkata", aliases: ["shopping mall", "rajdanga", "em bypass", "movies"] },
  { name: "Mani Square Mall, Kolkata", icon: Building2, category: "Mall", district: "Kolkata", aliases: ["shopping mall", "em bypass", "inox", "movies"] },
  { name: "City Centre Salt Lake, Kolkata", icon: Building2, category: "Mall", district: "North 24 Parganas", aliases: ["shopping mall", "movies", "food court"] },
  { name: "City Centre New Town, Kolkata", icon: Building2, category: "Mall", district: "North 24 Parganas", aliases: ["shopping mall", "movies", "food court"] },
  { name: "Avani Riverside Mall, Howrah", icon: Building2, category: "Mall", district: "Howrah", aliases: ["shopping mall", "movies", "howrah mall"] },
  
  // Universities
  { name: "Jadavpur University, Kolkata", icon: Landmark, category: "University", district: "Kolkata", aliases: ["ju", "engineering", "college", "admission"] },
  { name: "Calcutta University, College Street", icon: Landmark, category: "University", district: "Kolkata", aliases: ["cu", "college street", "admission", "oldest university"] },
  { name: "Presidency University, Kolkata", icon: Landmark, category: "University", district: "Kolkata", aliases: ["presidency college", "college street", "admission"] },
  { name: "IIT Kharagpur", icon: Landmark, category: "University", district: "West Midnapore", aliases: ["iit kgp", "engineering", "technology", "admission"] },
  { name: "IIM Calcutta, Joka", icon: Landmark, category: "University", district: "South 24 Parganas", aliases: ["iim c", "mba", "management", "admission"] },
  { name: "IIEST Shibpur, Howrah", icon: Landmark, category: "University", district: "Howrah", aliases: ["be college", "bengal engineering", "engineering"] },
  { name: "St. Xavier's College, Kolkata", icon: Landmark, category: "University", district: "Kolkata", aliases: ["xaviers", "college", "park street"] },
  
  // ==================== NORTH 24 PARGANAS ====================
  { name: "Barasat, North 24 Parganas", icon: Building2, category: "City", district: "North 24 Parganas", aliases: ["district hq", "subdivision"] },
  { name: "Barrackpore, North 24 Parganas", icon: Building2, category: "Town", district: "North 24 Parganas", aliases: ["barrackpur", "cantonment", "army"] },
  { name: "Madhyamgram, North 24 Parganas", icon: Building2, category: "Town", district: "North 24 Parganas", aliases: ["residential"] },
  { name: "Bongaon, North 24 Parganas", icon: Building2, category: "Town", district: "North 24 Parganas", aliases: ["border", "bangladesh border"] },
  { name: "Basirhat, North 24 Parganas", icon: Building2, category: "Town", district: "North 24 Parganas", aliases: ["subdivision"] },
  { name: "Habra, North 24 Parganas", icon: Building2, category: "Town", district: "North 24 Parganas" },
  { name: "Ashoknagar, North 24 Parganas", icon: Building2, category: "Town", district: "North 24 Parganas" },
  { name: "Gobardanga, North 24 Parganas", icon: Building2, category: "Town", district: "North 24 Parganas" },
  { name: "Naihati, North 24 Parganas", icon: Building2, category: "Town", district: "North 24 Parganas", aliases: ["junction"] },
  { name: "Titagarh, North 24 Parganas", icon: Building2, category: "Town", district: "North 24 Parganas" },
  { name: "Khardaha, North 24 Parganas", icon: Building2, category: "Town", district: "North 24 Parganas" },
  { name: "Panihati, North 24 Parganas", icon: Building2, category: "Town", district: "North 24 Parganas" },
  { name: "Kamarhati, North 24 Parganas", icon: Building2, category: "Town", district: "North 24 Parganas" },
  { name: "Sodepur, North 24 Parganas", icon: Building2, category: "Town", district: "North 24 Parganas" },
  { name: "Bijpur, North 24 Parganas", icon: Building2, category: "Town", district: "North 24 Parganas" },
  { name: "Gaighata, North 24 Parganas", icon: Building2, category: "Town", district: "North 24 Parganas" },
  { name: "Hasnabad, North 24 Parganas", icon: Building2, category: "Town", district: "North 24 Parganas" },
  { name: "Hingalganj, North 24 Parganas", icon: Building2, category: "Town", district: "North 24 Parganas" },
  { name: "Minakhan, North 24 Parganas", icon: Building2, category: "Town", district: "North 24 Parganas" },
  { name: "Sandeshkhali, North 24 Parganas", icon: Building2, category: "Town", district: "North 24 Parganas" },
  
  // ==================== SOUTH 24 PARGANAS ====================
  { name: "Baruipur, South 24 Parganas", icon: Building2, category: "Town", district: "South 24 Parganas", aliases: ["subdivision"] },
  { name: "Canning, South 24 Parganas", icon: Building2, category: "Town", district: "South 24 Parganas", aliases: ["sundarbans gateway"] },
  { name: "Diamond Harbour, South 24 Parganas", icon: Ship, category: "Town", district: "South 24 Parganas", aliases: ["river", "ganga", "picnic spot", "weekend"] },
  { name: "Kakdwip, South 24 Parganas", icon: Building2, category: "Town", district: "South 24 Parganas", aliases: ["ferry", "sagar island"] },
  { name: "Namkhana, South 24 Parganas", icon: Building2, category: "Town", district: "South 24 Parganas" },
  { name: "Sagar Island, South 24 Parganas", icon: Ship, category: "Island", district: "South 24 Parganas", aliases: ["gangasagar", "pilgrimage", "mela"] },
  { name: "Gangasagar, South 24 Parganas", icon: Landmark, category: "Pilgrimage", district: "South 24 Parganas", aliases: ["sagar", "kapil muni", "makar sankranti", "mela", "religious"] },
  { name: "Bakkhali Beach, South 24 Parganas", icon: Ship, category: "Beach", district: "South 24 Parganas", aliases: ["sea beach", "weekend", "vacation", "holiday"] },
  { name: "Frazerganj Beach, South 24 Parganas", icon: Ship, category: "Beach", district: "South 24 Parganas", aliases: ["sea beach", "weekend", "vacation"] },
  { name: "Henry Island, South 24 Parganas", icon: Ship, category: "Island", district: "South 24 Parganas", aliases: ["beach", "weekend"] },
  { name: "Sundarbans, South 24 Parganas", icon: TreePine, category: "Wildlife", district: "South 24 Parganas", aliases: ["tiger reserve", "mangrove", "forest", "safari", "royal bengal tiger", "unesco", "world heritage"] },
  { name: "Gosaba, South 24 Parganas", icon: Building2, category: "Town", district: "South 24 Parganas", aliases: ["sundarbans"] },
  { name: "Basanti, South 24 Parganas", icon: Building2, category: "Town", district: "South 24 Parganas" },
  { name: "Kultali, South 24 Parganas", icon: Building2, category: "Town", district: "South 24 Parganas" },
  { name: "Mathurapur, South 24 Parganas", icon: Building2, category: "Town", district: "South 24 Parganas" },
  { name: "Joynagar, South 24 Parganas", icon: Building2, category: "Town", district: "South 24 Parganas", aliases: ["moa", "sweets"] },
  { name: "Budge Budge, South 24 Parganas", icon: Building2, category: "Town", district: "South 24 Parganas" },
  { name: "Maheshtala, South 24 Parganas", icon: Building2, category: "Town", district: "South 24 Parganas" },
  { name: "Rajpur, South 24 Parganas", icon: Building2, category: "Town", district: "South 24 Parganas" },
  
  // ==================== HOWRAH ====================
  { name: "Howrah City, Howrah", icon: Building2, category: "City", district: "Howrah", aliases: ["district hq"] },
  { name: "Uluberia, Howrah", icon: Building2, category: "Town", district: "Howrah", aliases: ["subdivision"] },
  { name: "Shyampur, Howrah", icon: Building2, category: "Town", district: "Howrah" },
  { name: "Bagnan, Howrah", icon: Building2, category: "Town", district: "Howrah" },
  { name: "Amta, Howrah", icon: Building2, category: "Town", district: "Howrah" },
  { name: "Udaynarayanpur, Howrah", icon: Building2, category: "Town", district: "Howrah" },
  { name: "Jagatballavpur, Howrah", icon: Building2, category: "Town", district: "Howrah" },
  { name: "Domjur, Howrah", icon: Building2, category: "Town", district: "Howrah" },
  { name: "Panchla, Howrah", icon: Building2, category: "Town", district: "Howrah" },
  
  // ==================== HOOGHLY ====================
  { name: "Chinsurah, Hooghly", icon: Building2, category: "City", district: "Hooghly", aliases: ["district hq", "chuchura"] },
  { name: "Chandannagar, Hooghly", icon: Building2, category: "City", district: "Hooghly", aliases: ["french colony", "jagaddhatri puja"] },
  { name: "Serampore, Hooghly", icon: Building2, category: "City", district: "Hooghly", aliases: ["danish colony", "printing press"] },
  { name: "Rishra, Hooghly", icon: Building2, category: "Town", district: "Hooghly" },
  { name: "Bandel, Hooghly", icon: Train, category: "Town", district: "Hooghly", aliases: ["junction", "railway"] },
  { name: "Bandel Church, Hooghly", icon: Landmark, category: "Church", district: "Hooghly", aliases: ["basilica", "portuguese", "christian", "religious"] },
  { name: "Tarakeswar, Hooghly", icon: Landmark, category: "Temple", district: "Hooghly", aliases: ["tarakeshwar", "shiva temple", "religious", "pilgrimage"] },
  { name: "Arambagh, Hooghly", icon: Building2, category: "Town", district: "Hooghly", aliases: ["subdivision"] },
  { name: "Khanakul, Hooghly", icon: Building2, category: "Town", district: "Hooghly" },
  { name: "Pursurah, Hooghly", icon: Building2, category: "Town", district: "Hooghly" },
  { name: "Goghat, Hooghly", icon: Building2, category: "Town", district: "Hooghly" },
  { name: "Polba, Hooghly", icon: Building2, category: "Town", district: "Hooghly" },
  { name: "Singur, Hooghly", icon: Building2, category: "Town", district: "Hooghly" },
  { name: "Haripal, Hooghly", icon: Building2, category: "Town", district: "Hooghly" },
  { name: "Dhanekhali, Hooghly", icon: Building2, category: "Town", district: "Hooghly" },
  { name: "Tribeni, Hooghly", icon: Landmark, category: "Town", district: "Hooghly", aliases: ["sangam", "three rivers"] },
  { name: "Mogra, Hooghly", icon: Building2, category: "Town", district: "Hooghly" },
  { name: "Uttarpara, Hooghly", icon: Building2, category: "Town", district: "Hooghly" },
  { name: "Dankuni, Hooghly", icon: Building2, category: "Town", district: "Hooghly", aliases: ["expressway"] },
  
  // ==================== NADIA ====================
  { name: "Krishnanagar, Nadia", icon: Building2, category: "City", district: "Nadia", aliases: ["district hq", "clay dolls", "terracotta"] },
  { name: "Nabadwip, Nadia", icon: Landmark, category: "Pilgrimage", district: "Nadia", aliases: ["navadwip", "chaitanya", "gaudiya vaishnav", "religious"] },
  { name: "Mayapur (ISKCON), Nadia", icon: Landmark, category: "Temple", district: "Nadia", aliases: ["iskcon", "hare krishna", "tvp", "religious", "pilgrimage"] },
  { name: "Ranaghat, Nadia", icon: Train, category: "Town", district: "Nadia", aliases: ["junction", "railway"] },
  { name: "Shantipur, Nadia", icon: Building2, category: "Town", district: "Nadia", aliases: ["tant saree", "handloom"] },
  { name: "Chakdaha, Nadia", icon: Building2, category: "Town", district: "Nadia" },
  { name: "Kalyani, Nadia", icon: Building2, category: "Town", district: "Nadia", aliases: ["university", "expressway"] },
  { name: "Gayeshpur, Nadia", icon: Building2, category: "Town", district: "Nadia" },
  { name: "Tehatta, Nadia", icon: Building2, category: "Town", district: "Nadia" },
  { name: "Karimpur, Nadia", icon: Building2, category: "Town", district: "Nadia" },
  { name: "Nakashipara, Nadia", icon: Building2, category: "Town", district: "Nadia" },
  { name: "Chapra, Nadia", icon: Building2, category: "Town", district: "Nadia" },
  { name: "Bethuadahari, Nadia", icon: Building2, category: "Town", district: "Nadia", aliases: ["wildlife sanctuary", "deer park"] },
  { name: "Hanskhali, Nadia", icon: Building2, category: "Town", district: "Nadia" },
  
  // ==================== MURSHIDABAD ====================
  { name: "Berhampore, Murshidabad", icon: Building2, category: "City", district: "Murshidabad", aliases: ["district hq", "baharampur"] },
  { name: "Murshidabad (Hazarduari), Murshidabad", icon: Landmark, category: "Heritage", district: "Murshidabad", aliases: ["1000 doors", "palace", "nawab", "history"] },
  { name: "Lalbagh Court, Murshidabad", icon: Landmark, category: "Heritage", district: "Murshidabad", aliases: ["nawab palace", "history"] },
  { name: "Katra Mosque, Murshidabad", icon: Landmark, category: "Heritage", district: "Murshidabad", aliases: ["historical", "mughal"] },
  { name: "Jiaganj, Murshidabad", icon: Building2, category: "Town", district: "Murshidabad" },
  { name: "Jangipur, Murshidabad", icon: Building2, category: "Town", district: "Murshidabad", aliases: ["subdivision"] },
  { name: "Farakka, Murshidabad", icon: Building2, category: "Town", district: "Murshidabad", aliases: ["barrage", "dam", "ganga"] },
  { name: "Suti, Murshidabad", icon: Building2, category: "Town", district: "Murshidabad" },
  { name: "Kandi, Murshidabad", icon: Building2, category: "Town", district: "Murshidabad", aliases: ["subdivision"] },
  { name: "Domkal, Murshidabad", icon: Building2, category: "Town", district: "Murshidabad" },
  { name: "Lalgola, Murshidabad", icon: Building2, category: "Town", district: "Murshidabad", aliases: ["border", "bangladesh"] },
  { name: "Raghunathganj, Murshidabad", icon: Building2, category: "Town", district: "Murshidabad" },
  { name: "Sagardighi, Murshidabad", icon: Building2, category: "Town", district: "Murshidabad" },
  { name: "Khargram, Murshidabad", icon: Building2, category: "Town", district: "Murshidabad" },
  { name: "Nabagram, Murshidabad", icon: Building2, category: "Town", district: "Murshidabad" },
  
  // ==================== BIRBHUM ====================
  { name: "Suri, Birbhum", icon: Building2, category: "City", district: "Birbhum", aliases: ["district hq"] },
  { name: "Shantiniketan, Birbhum", icon: Landmark, category: "Heritage", district: "Birbhum", aliases: ["rabindranath", "tagore", "visva bharati", "poush mela", "cultural"] },
  { name: "Visva Bharati University, Shantiniketan", icon: Landmark, category: "University", district: "Birbhum", aliases: ["rabindranath", "tagore", "admission"] },
  { name: "Bolpur, Birbhum", icon: Train, category: "Town", district: "Birbhum", aliases: ["shantiniketan station", "railway"] },
  { name: "Rampurhat, Birbhum", icon: Building2, category: "Town", district: "Birbhum", aliases: ["subdivision"] },
  { name: "Sainthia, Birbhum", icon: Building2, category: "Town", district: "Birbhum", aliases: ["junction"] },
  { name: "Dubrajpur, Birbhum", icon: Building2, category: "Town", district: "Birbhum" },
  { name: "Nalhati, Birbhum", icon: Building2, category: "Town", district: "Birbhum" },
  { name: "Mohammad Bazar, Birbhum", icon: Building2, category: "Town", district: "Birbhum" },
  { name: "Labhpur, Birbhum", icon: Building2, category: "Town", district: "Birbhum" },
  { name: "Nanoor, Birbhum", icon: Building2, category: "Town", district: "Birbhum" },
  { name: "Illambazar, Birbhum", icon: Building2, category: "Town", district: "Birbhum" },
  { name: "Murarai, Birbhum", icon: Building2, category: "Town", district: "Birbhum" },
  { name: "Tarapith, Birbhum", icon: Landmark, category: "Temple", district: "Birbhum", aliases: ["tara ma", "shakti peeth", "tantric", "religious", "pilgrimage"] },
  { name: "Bakreshwar, Birbhum", icon: Landmark, category: "Temple", district: "Birbhum", aliases: ["hot spring", "thermal spring", "religious"] },
  
  // ==================== BARDHAMAN (PURBA & PASCHIM) ====================
  { name: "Bardhaman City (Burdwan)", icon: Building2, category: "City", district: "Purba Bardhaman", aliases: ["district hq", "barddhaman"] },
  { name: "Bardhaman Station", icon: Train, category: "Railway Station", district: "Purba Bardhaman", aliases: ["bwn", "junction", "railway"] },
  { name: "Durgapur, Paschim Bardhaman", icon: Building2, category: "City", district: "Paschim Bardhaman", aliases: ["steel city", "industrial", "dsp"] },
  { name: "Asansol, Paschim Bardhaman", icon: Building2, category: "City", district: "Paschim Bardhaman", aliases: ["coal city", "industrial", "subdivision"] },
  { name: "Asansol Station", icon: Train, category: "Railway Station", district: "Paschim Bardhaman", aliases: ["asl", "junction", "railway"] },
  { name: "Raniganj, Paschim Bardhaman", icon: Building2, category: "Town", district: "Paschim Bardhaman", aliases: ["coal mines"] },
  { name: "Kulti, Paschim Bardhaman", icon: Building2, category: "Town", district: "Paschim Bardhaman" },
  { name: "Andal, Paschim Bardhaman", icon: Plane, category: "Airport", district: "Paschim Bardhaman", aliases: ["kazi nazrul islam airport", "durgapur airport", "flight"] },
  { name: "Burnpur, Paschim Bardhaman", icon: Building2, category: "Town", district: "Paschim Bardhaman", aliases: ["iisco", "steel plant"] },
  { name: "Jamuria, Paschim Bardhaman", icon: Building2, category: "Town", district: "Paschim Bardhaman" },
  { name: "Ondal, Paschim Bardhaman", icon: Building2, category: "Town", district: "Paschim Bardhaman" },
  { name: "Kalna, Purba Bardhaman", icon: Landmark, category: "Town", district: "Purba Bardhaman", aliases: ["temples", "terracotta"] },
  { name: "Katwa, Purba Bardhaman", icon: Building2, category: "Town", district: "Purba Bardhaman", aliases: ["junction"] },
  { name: "Memari, Purba Bardhaman", icon: Building2, category: "Town", district: "Purba Bardhaman" },
  { name: "Ausgram, Purba Bardhaman", icon: Building2, category: "Town", district: "Purba Bardhaman" },
  { name: "Galsi, Purba Bardhaman", icon: Building2, category: "Town", district: "Purba Bardhaman" },
  { name: "Monteswar, Purba Bardhaman", icon: Building2, category: "Town", district: "Purba Bardhaman" },
  { name: "Guskara, Purba Bardhaman", icon: Building2, category: "Town", district: "Purba Bardhaman" },
  
  // ==================== BANKURA ====================
  { name: "Bankura City, Bankura", icon: Building2, category: "City", district: "Bankura", aliases: ["district hq"] },
  { name: "Bishnupur, Bankura", icon: Landmark, category: "Heritage", district: "Bankura", aliases: ["terracotta", "temples", "malla kings", "baluchari", "unesco"] },
  { name: "Rasmancha, Bishnupur", icon: Landmark, category: "Heritage", district: "Bankura", aliases: ["unique temple", "pyramidal"] },
  { name: "Terracotta Temples, Bishnupur", icon: Landmark, category: "Heritage", district: "Bankura", aliases: ["jor bangla", "shyam rai", "historical"] },
  { name: "Mukutmanipur, Bankura", icon: TreePine, category: "Tourist", district: "Bankura", aliases: ["dam", "reservoir", "picnic", "weekend"] },
  { name: "Susunia Hill, Bankura", icon: TreePine, category: "Tourist", district: "Bankura", aliases: ["trekking", "rock climbing", "picnic"] },
  { name: "Jhilimili, Bankura", icon: TreePine, category: "Tourist", district: "Bankura", aliases: ["forest", "nature", "tribal"] },
  { name: "Kotulpur, Bankura", icon: Building2, category: "Town", district: "Bankura" },
  { name: "Sonamukhi, Bankura", icon: Building2, category: "Town", district: "Bankura" },
  { name: "Onda, Bankura", icon: Building2, category: "Town", district: "Bankura" },
  { name: "Mejhia, Bankura", icon: Building2, category: "Town", district: "Bankura" },
  { name: "Khatra, Bankura", icon: Building2, category: "Town", district: "Bankura", aliases: ["subdivision"] },
  { name: "Ranibandh, Bankura", icon: Building2, category: "Town", district: "Bankura" },
  { name: "Sarenga, Bankura", icon: Building2, category: "Town", district: "Bankura" },
  
  // ==================== PURULIA ====================
  { name: "Purulia City, Purulia", icon: Building2, category: "City", district: "Purulia", aliases: ["district hq", "chhau dance"] },
  { name: "Ayodhya Hills, Purulia", icon: TreePine, category: "Hill", district: "Purulia", aliases: ["ajodhya", "trekking", "camping", "nature", "weekend"] },
  { name: "Ajodhya Pahar, Purulia", icon: TreePine, category: "Hill", district: "Purulia", aliases: ["ayodhya", "hills", "trekking"] },
  { name: "Baranti Lake, Purulia", icon: TreePine, category: "Tourist", district: "Purulia", aliases: ["muradi", "camping", "sunset", "weekend"] },
  { name: "Matha Forest, Purulia", icon: TreePine, category: "Nature", district: "Purulia", aliases: ["sal forest", "nature"] },
  { name: "Raghunathpur, Purulia", icon: Building2, category: "Town", district: "Purulia", aliases: ["subdivision"] },
  { name: "Adra, Purulia", icon: Train, category: "Town", district: "Purulia", aliases: ["junction", "railway"] },
  { name: "Jhalda, Purulia", icon: Building2, category: "Town", district: "Purulia" },
  { name: "Balarampur, Purulia", icon: Building2, category: "Town", district: "Purulia" },
  { name: "Manbazar, Purulia", icon: Building2, category: "Town", district: "Purulia" },
  { name: "Bundwan, Purulia", icon: Building2, category: "Town", district: "Purulia" },
  { name: "Arsha, Purulia", icon: Building2, category: "Town", district: "Purulia" },
  { name: "Bagmundi, Purulia", icon: Building2, category: "Town", district: "Purulia", aliases: ["ayodhya hills base"] },
  { name: "Kashipur, Purulia", icon: Building2, category: "Town", district: "Purulia" },
  { name: "Para, Purulia", icon: Building2, category: "Town", district: "Purulia" },
  { name: "Neturia, Purulia", icon: Building2, category: "Town", district: "Purulia" },
  
  // ==================== EAST MIDNAPORE ====================
  { name: "Tamluk, East Midnapore", icon: Building2, category: "City", district: "East Midnapore", aliases: ["district hq", "tamralipta"] },
  { name: "Haldia, East Midnapore", icon: Building2, category: "City", district: "East Midnapore", aliases: ["port", "industrial", "refinery"] },
  { name: "Haldia Port, East Midnapore", icon: Ship, category: "Port", district: "East Midnapore", aliases: ["shipping", "cargo"] },
  { name: "Contai, East Midnapore", icon: Building2, category: "Town", district: "East Midnapore", aliases: ["kanthi", "subdivision"] },
  { name: "Digha Beach, East Midnapore", icon: Ship, category: "Beach", district: "East Midnapore", aliases: ["sea beach", "vacation", "holiday", "weekend", "ocean", "sea"] },
  { name: "New Digha, East Midnapore", icon: Ship, category: "Beach", district: "East Midnapore", aliases: ["beach", "hotels", "resorts"] },
  { name: "Old Digha, East Midnapore", icon: Ship, category: "Beach", district: "East Midnapore", aliases: ["beach", "market"] },
  { name: "Mandarmani Beach, East Midnapore", icon: Ship, category: "Beach", district: "East Midnapore", aliases: ["sea beach", "longest beach", "resort", "weekend", "vacation"] },
  { name: "Tajpur Beach, East Midnapore", icon: Ship, category: "Beach", district: "East Midnapore", aliases: ["sea beach", "red crabs", "virgin beach", "weekend"] },
  { name: "Shankarpur Beach, East Midnapore", icon: Ship, category: "Beach", district: "East Midnapore", aliases: ["sea beach", "fishing village"] },
  { name: "Junput Beach, East Midnapore", icon: Ship, category: "Beach", district: "East Midnapore", aliases: ["sea beach", "quiet beach"] },
  { name: "Mecheda, East Midnapore", icon: Building2, category: "Town", district: "East Midnapore" },
  { name: "Kolaghat, East Midnapore", icon: Building2, category: "Town", district: "East Midnapore", aliases: ["thermal power"] },
  { name: "Panskura, East Midnapore", icon: Building2, category: "Town", district: "East Midnapore" },
  { name: "Egra, East Midnapore", icon: Building2, category: "Town", district: "East Midnapore" },
  { name: "Khejuri, East Midnapore", icon: Building2, category: "Town", district: "East Midnapore" },
  { name: "Nandigram, East Midnapore", icon: Building2, category: "Town", district: "East Midnapore" },
  { name: "Sutahata, East Midnapore", icon: Building2, category: "Town", district: "East Midnapore" },
  { name: "Bhagwanpur, East Midnapore", icon: Building2, category: "Town", district: "East Midnapore" },
  { name: "Ramnagar, East Midnapore", icon: Building2, category: "Town", district: "East Midnapore" },
  { name: "Chandipur, East Midnapore", icon: Building2, category: "Town", district: "East Midnapore", aliases: ["drdo", "missile test"] },
  
  // ==================== WEST MIDNAPORE ====================
  { name: "Midnapore City, West Midnapore", icon: Building2, category: "City", district: "West Midnapore", aliases: ["district hq", "medinipur"] },
  { name: "Kharagpur, West Midnapore", icon: Train, category: "City", district: "West Midnapore", aliases: ["iit", "railway", "junction"] },
  { name: "Kharagpur Railway Station", icon: Train, category: "Railway Station", district: "West Midnapore", aliases: ["kgp", "longest platform", "railway"] },
  { name: "Ghatal, West Midnapore", icon: Building2, category: "Town", district: "West Midnapore", aliases: ["subdivision"] },
  { name: "Keshpur, West Midnapore", icon: Building2, category: "Town", district: "West Midnapore" },
  { name: "Garbeta, West Midnapore", icon: Building2, category: "Town", district: "West Midnapore" },
  { name: "Debra, West Midnapore", icon: Building2, category: "Town", district: "West Midnapore" },
  { name: "Pingla, West Midnapore", icon: Building2, category: "Town", district: "West Midnapore" },
  { name: "Dantan, West Midnapore", icon: Building2, category: "Town", district: "West Midnapore" },
  { name: "Mohanpur, West Midnapore", icon: Building2, category: "Town", district: "West Midnapore" },
  { name: "Narayangarh, West Midnapore", icon: Building2, category: "Town", district: "West Midnapore" },
  { name: "Sabang, West Midnapore", icon: Building2, category: "Town", district: "West Midnapore" },
  { name: "Salboni, West Midnapore", icon: Building2, category: "Town", district: "West Midnapore" },
  { name: "Belda, West Midnapore", icon: Building2, category: "Town", district: "West Midnapore" },
  
  // ==================== JHARGRAM ====================
  { name: "Jhargram, Jhargram", icon: Building2, category: "City", district: "Jhargram", aliases: ["district hq", "forest"] },
  { name: "Jhargram Raj Palace", icon: Landmark, category: "Heritage", district: "Jhargram", aliases: ["royal palace", "museum"] },
  { name: "Belpahari, Jhargram", icon: TreePine, category: "Nature", district: "Jhargram", aliases: ["forest", "tribal", "nature"] },
  { name: "Kankrajhore, Jhargram", icon: TreePine, category: "Nature", district: "Jhargram", aliases: ["forest", "nature"] },
  { name: "Gopiballavpur, Jhargram", icon: Building2, category: "Town", district: "Jhargram" },
  { name: "Nayagram, Jhargram", icon: Building2, category: "Town", district: "Jhargram" },
  { name: "Binpur, Jhargram", icon: Building2, category: "Town", district: "Jhargram" },
  { name: "Jamboni, Jhargram", icon: Building2, category: "Town", district: "Jhargram" },
  { name: "Lalgarh, Jhargram", icon: Building2, category: "Town", district: "Jhargram" },
  { name: "Sankrail, Jhargram", icon: Building2, category: "Town", district: "Jhargram" },
  
  // ==================== MALDA ====================
  { name: "Malda City (English Bazar)", icon: Building2, category: "City", district: "Malda", aliases: ["district hq", "mango city"] },
  { name: "Malda Station", icon: Train, category: "Railway Station", district: "Malda", aliases: ["railway", "mldt"] },
  { name: "Gaur, Malda", icon: Landmark, category: "Heritage", district: "Malda", aliases: ["gour", "ancient capital", "ruins", "historical"] },
  { name: "Pandua, Malda", icon: Landmark, category: "Heritage", district: "Malda", aliases: ["adina mosque", "historical", "sultanate"] },
  { name: "Adina Mosque, Malda", icon: Landmark, category: "Heritage", district: "Malda", aliases: ["largest mosque", "historical", "sultanate"] },
  { name: "Old Malda, Malda", icon: Building2, category: "Town", district: "Malda" },
  { name: "Kaliachak, Malda", icon: Building2, category: "Town", district: "Malda" },
  { name: "Harischandrapur, Malda", icon: Building2, category: "Town", district: "Malda" },
  { name: "Chanchal, Malda", icon: Building2, category: "Town", district: "Malda", aliases: ["subdivision"] },
  { name: "Ratua, Malda", icon: Building2, category: "Town", district: "Malda" },
  { name: "Habibpur, Malda", icon: Building2, category: "Town", district: "Malda" },
  { name: "Gazole, Malda", icon: Building2, category: "Town", district: "Malda" },
  { name: "Manikchak, Malda", icon: Building2, category: "Town", district: "Malda" },
  { name: "Bamongola, Malda", icon: Building2, category: "Town", district: "Malda" },
  
  // ==================== UTTAR DINAJPUR ====================
  { name: "Raiganj, Uttar Dinajpur", icon: Building2, category: "City", district: "Uttar Dinajpur", aliases: ["district hq"] },
  { name: "Raiganj Wildlife Sanctuary", icon: TreePine, category: "Wildlife", district: "Uttar Dinajpur", aliases: ["bird sanctuary", "birds", "kulik"] },
  { name: "Islampur, Uttar Dinajpur", icon: Building2, category: "Town", district: "Uttar Dinajpur", aliases: ["subdivision"] },
  { name: "Dalkhola, Uttar Dinajpur", icon: Building2, category: "Town", district: "Uttar Dinajpur" },
  { name: "Kaliaganj, Uttar Dinajpur", icon: Building2, category: "Town", district: "Uttar Dinajpur" },
  { name: "Hemtabad, Uttar Dinajpur", icon: Building2, category: "Town", district: "Uttar Dinajpur" },
  { name: "Itahar, Uttar Dinajpur", icon: Building2, category: "Town", district: "Uttar Dinajpur" },
  { name: "Karandighi, Uttar Dinajpur", icon: Building2, category: "Town", district: "Uttar Dinajpur" },
  { name: "Chopra, Uttar Dinajpur", icon: Building2, category: "Town", district: "Uttar Dinajpur" },
  { name: "Goalpokhar, Uttar Dinajpur", icon: Building2, category: "Town", district: "Uttar Dinajpur" },
  
  // ==================== DAKSHIN DINAJPUR ====================
  { name: "Balurghat, Dakshin Dinajpur", icon: Building2, category: "City", district: "Dakshin Dinajpur", aliases: ["district hq"] },
  { name: "Gangarampur, Dakshin Dinajpur", icon: Building2, category: "Town", district: "Dakshin Dinajpur" },
  { name: "Buniadpur, Dakshin Dinajpur", icon: Building2, category: "Town", district: "Dakshin Dinajpur" },
  { name: "Kumarganj, Dakshin Dinajpur", icon: Building2, category: "Town", district: "Dakshin Dinajpur" },
  { name: "Tapan, Dakshin Dinajpur", icon: Building2, category: "Town", district: "Dakshin Dinajpur" },
  { name: "Kushmandi, Dakshin Dinajpur", icon: Building2, category: "Town", district: "Dakshin Dinajpur" },
  { name: "Hili, Dakshin Dinajpur", icon: Building2, category: "Town", district: "Dakshin Dinajpur", aliases: ["border", "bangladesh"] },
  { name: "Bansihari, Dakshin Dinajpur", icon: Building2, category: "Town", district: "Dakshin Dinajpur" },
  
  // ==================== DARJEELING ====================
  { name: "Darjeeling Town, Darjeeling", icon: TreePine, category: "Hill Station", district: "Darjeeling", aliases: ["queen of hills", "tea garden", "mountain", "himalaya", "vacation", "honeymoon"] },
  { name: "Darjeeling Railway Station (DHR)", icon: Train, category: "Railway Station", district: "Darjeeling", aliases: ["toy train", "heritage railway", "unesco"] },
  { name: "Tiger Hill, Darjeeling", icon: TreePine, category: "View Point", district: "Darjeeling", aliases: ["sunrise", "kanchenjunga view", "mount everest view"] },
  { name: "Batasia Loop, Darjeeling", icon: Landmark, category: "Landmark", district: "Darjeeling", aliases: ["toy train", "war memorial", "garden"] },
  { name: "Mall Road, Darjeeling", icon: Building2, category: "Area", district: "Darjeeling", aliases: ["shopping", "walking", "chowrasta"] },
  { name: "Chowrasta, Darjeeling", icon: Building2, category: "Area", district: "Darjeeling", aliases: ["mall", "walking", "viewpoint"] },
  { name: "Ghum, Darjeeling", icon: Train, category: "Town", district: "Darjeeling", aliases: ["ghoom", "highest railway station", "toy train"] },
  { name: "Himalayan Mountaineering Institute", icon: Landmark, category: "Museum", district: "Darjeeling", aliases: ["hmi", "tenzing norgay", "everest", "climbing"] },
  { name: "Padmaja Naidu Zoo, Darjeeling", icon: TreePine, category: "Zoo", district: "Darjeeling", aliases: ["zoo", "red panda", "snow leopard", "himalayan animals"] },
  { name: "Japanese Temple, Darjeeling", icon: Landmark, category: "Temple", district: "Darjeeling", aliases: ["peace pagoda", "buddhist", "nipponzan"] },
  { name: "Peace Pagoda, Darjeeling", icon: Landmark, category: "Temple", district: "Darjeeling", aliases: ["japanese temple", "buddhist"] },
  { name: "Rock Garden, Darjeeling", icon: TreePine, category: "Tourist", district: "Darjeeling", aliases: ["barbotey", "chunnu summer falls", "garden"] },
  { name: "Happy Valley Tea Estate", icon: TreePine, category: "Tea Garden", district: "Darjeeling", aliases: ["tea factory", "tea tasting", "organic tea"] },
  { name: "Mirik, Darjeeling", icon: TreePine, category: "Hill Station", district: "Darjeeling", aliases: ["sumendu lake", "boating", "orange orchard"] },
  { name: "Mirik Lake, Darjeeling", icon: TreePine, category: "Lake", district: "Darjeeling", aliases: ["sumendu lake", "boating"] },
  { name: "Kurseong, Darjeeling", icon: TreePine, category: "Hill Station", district: "Darjeeling", aliases: ["land of orchids", "tea gardens"] },
  { name: "Kurseong Station", icon: Train, category: "Railway Station", district: "Darjeeling", aliases: ["toy train", "dhr"] },
  { name: "Dow Hill, Kurseong", icon: TreePine, category: "View Point", district: "Darjeeling", aliases: ["forest", "haunted", "victoria boys school"] },
  { name: "Eagle's Crag, Kurseong", icon: TreePine, category: "View Point", district: "Darjeeling", aliases: ["viewpoint", "sunset"] },
  { name: "Sukhiapokhri, Darjeeling", icon: Building2, category: "Town", district: "Darjeeling" },
  { name: "Sonada, Darjeeling", icon: Building2, category: "Town", district: "Darjeeling" },
  { name: "Jorebunglow, Darjeeling", icon: Building2, category: "Town", district: "Darjeeling" },
  { name: "Sukna, Darjeeling", icon: Building2, category: "Town", district: "Darjeeling", aliases: ["army", "salugara"] },
  
  // ==================== KALIMPONG ====================
  { name: "Kalimpong Town, Kalimpong", icon: TreePine, category: "Hill Station", district: "Kalimpong", aliases: ["nursery", "orchids", "flowers", "cactus"] },
  { name: "Deolo Hill, Kalimpong", icon: TreePine, category: "View Point", district: "Kalimpong", aliases: ["highest point", "sunrise", "picnic"] },
  { name: "Durpin Monastery, Kalimpong", icon: Landmark, category: "Monastery", district: "Kalimpong", aliases: ["zang dhok palri", "buddhist", "prayer wheel"] },
  { name: "Thongsa Gumpha, Kalimpong", icon: Landmark, category: "Monastery", district: "Kalimpong", aliases: ["bhutanese monastery", "buddhist"] },
  { name: "Cactus Nursery, Kalimpong", icon: TreePine, category: "Nursery", district: "Kalimpong", aliases: ["pine view nursery", "cactus", "plants"] },
  { name: "Lava, Kalimpong", icon: TreePine, category: "Hill Station", district: "Kalimpong", aliases: ["nature camp", "forest", "trekking", "offbeat"] },
  { name: "Lolegaon, Kalimpong", icon: TreePine, category: "Hill Station", district: "Kalimpong", aliases: ["canopy walk", "forest", "offbeat"] },
  { name: "Rishyap, Kalimpong", icon: TreePine, category: "Hill Station", district: "Kalimpong", aliases: ["rishop", "kanchenjunga view", "offbeat"] },
  { name: "Pedong, Kalimpong", icon: Building2, category: "Town", district: "Kalimpong" },
  { name: "Algarah, Kalimpong", icon: Building2, category: "Town", district: "Kalimpong" },
  { name: "Gorubathan, Kalimpong", icon: Building2, category: "Town", district: "Kalimpong" },
  
  // ==================== JALPAIGURI ====================
  { name: "Jalpaiguri City, Jalpaiguri", icon: Building2, category: "City", district: "Jalpaiguri", aliases: ["district hq", "jpg"] },
  { name: "Jalpaiguri Station", icon: Train, category: "Railway Station", district: "Jalpaiguri", aliases: ["railway"] },
  { name: "Mainaguri, Jalpaiguri", icon: Building2, category: "Town", district: "Jalpaiguri" },
  { name: "Mal, Jalpaiguri", icon: Building2, category: "Town", district: "Jalpaiguri" },
  { name: "Nagrakata, Jalpaiguri", icon: Building2, category: "Town", district: "Jalpaiguri" },
  { name: "Matelli, Jalpaiguri", icon: Building2, category: "Town", district: "Jalpaiguri" },
  { name: "Dhupguri, Jalpaiguri", icon: Building2, category: "Town", district: "Jalpaiguri" },
  { name: "Malbazar, Jalpaiguri", icon: Building2, category: "Town", district: "Jalpaiguri", aliases: ["subdivision", "mal bazar"] },
  { name: "Chalsa, Jalpaiguri", icon: Building2, category: "Town", district: "Jalpaiguri", aliases: ["dooars", "tea garden"] },
  { name: "Gorumara National Park", icon: TreePine, category: "Wildlife", district: "Jalpaiguri", aliases: ["jungle safari", "rhino", "elephant", "dooars", "forest"] },
  { name: "Chapramari Wildlife Sanctuary", icon: TreePine, category: "Wildlife", district: "Jalpaiguri", aliases: ["elephant corridor", "dooars"] },
  { name: "Buxa Tiger Reserve", icon: TreePine, category: "Wildlife", district: "Jalpaiguri", aliases: ["tiger", "dooars", "trekking", "fort"] },
  { name: "Rajabhatkhawa, Jalpaiguri", icon: Building2, category: "Town", district: "Jalpaiguri", aliases: ["buxa", "nature interpretation centre"] },
  
  // ==================== ALIPURDUAR ====================
  { name: "Alipurduar City, Alipurduar", icon: Building2, category: "City", district: "Alipurduar", aliases: ["district hq"] },
  { name: "Alipurduar Junction Station", icon: Train, category: "Railway Station", district: "Alipurduar", aliases: ["apdj", "railway", "junction"] },
  { name: "Falakata, Alipurduar", icon: Building2, category: "Town", district: "Alipurduar" },
  { name: "Madarihat, Alipurduar", icon: Building2, category: "Town", district: "Alipurduar", aliases: ["jaldapara gate"] },
  { name: "Samuktala, Alipurduar", icon: Building2, category: "Town", district: "Alipurduar" },
  { name: "Kumargram, Alipurduar", icon: Building2, category: "Town", district: "Alipurduar" },
  { name: "Birpara, Alipurduar", icon: Building2, category: "Town", district: "Alipurduar" },
  { name: "Kalchini, Alipurduar", icon: Building2, category: "Town", district: "Alipurduar" },
  { name: "Jaldapara National Park", icon: TreePine, category: "Wildlife", district: "Alipurduar", aliases: ["rhino", "elephant safari", "dooars", "jungle"] },
  { name: "Hollong, Jaldapara", icon: TreePine, category: "Tourist", district: "Alipurduar", aliases: ["forest lodge", "safari"] },
  { name: "Chilapata Forest, Alipurduar", icon: TreePine, category: "Nature", district: "Alipurduar", aliases: ["dooars", "jungle", "elephant"] },
  { name: "Buxa Fort, Alipurduar", icon: Landmark, category: "Heritage", district: "Alipurduar", aliases: ["historical", "trekking", "freedom fighters"] },
  { name: "Jayanti, Alipurduar", icon: TreePine, category: "Nature", district: "Alipurduar", aliases: ["river", "buxa", "offbeat"] },
  { name: "Phuentsholing (Bhutan Border)", icon: Building2, category: "Border", district: "Alipurduar", aliases: ["bhutan", "international border", "jaigaon"] },
  
  // ==================== COOCH BEHAR ====================
  { name: "Cooch Behar City, Cooch Behar", icon: Building2, category: "City", district: "Cooch Behar", aliases: ["district hq", "koch bihar"] },
  { name: "Cooch Behar Palace (Rajbari)", icon: Landmark, category: "Heritage", district: "Cooch Behar", aliases: ["victor jubilee palace", "buckingham palace", "royal palace"] },
  { name: "Madan Mohan Temple, Cooch Behar", icon: Landmark, category: "Temple", district: "Cooch Behar", aliases: ["hindu temple", "religious"] },
  { name: "Sagar Dighi, Cooch Behar", icon: TreePine, category: "Lake", district: "Cooch Behar", aliases: ["lake", "boating"] },
  { name: "Rasik Bil, Cooch Behar", icon: TreePine, category: "Wildlife", district: "Cooch Behar", aliases: ["bird sanctuary", "wetland"] },
  { name: "New Cooch Behar Station", icon: Train, category: "Railway Station", district: "Cooch Behar", aliases: ["ncb", "railway"] },
  { name: "Tufanganj, Cooch Behar", icon: Building2, category: "Town", district: "Cooch Behar", aliases: ["subdivision"] },
  { name: "Mathabhanga, Cooch Behar", icon: Building2, category: "Town", district: "Cooch Behar" },
  { name: "Dinhata, Cooch Behar", icon: Building2, category: "Town", district: "Cooch Behar", aliases: ["subdivision"] },
  { name: "Sitalkuchi, Cooch Behar", icon: Building2, category: "Town", district: "Cooch Behar" },
  { name: "Mekhliganj, Cooch Behar", icon: Building2, category: "Town", district: "Cooch Behar" },
  { name: "Haldibari, Cooch Behar", icon: Building2, category: "Town", district: "Cooch Behar" },
  { name: "Sitai, Cooch Behar", icon: Building2, category: "Town", district: "Cooch Behar" },
  
  // ==================== SILIGURI & SURROUNDING ====================
  { name: "Siliguri City, Darjeeling", icon: Building2, category: "City", district: "Darjeeling", aliases: ["gateway to northeast", "north bengal", "chicken neck"] },
  { name: "Siliguri Junction Station", icon: Train, category: "Railway Station", district: "Darjeeling", aliases: ["sguj", "railway", "junction"] },
  { name: "New Jalpaiguri Station (NJP)", icon: Train, category: "Railway Station", district: "Jalpaiguri", aliases: ["njp", "railway", "junction", "main station", "north bengal"] },
  { name: "Bagdogra Airport, Siliguri", icon: Plane, category: "Airport", district: "Darjeeling", aliases: ["north bengal airport", "siliguri airport", "ixa", "flight", "darjeeling airport"] },
  { name: "Tenzing Norgay Bus Stand, Siliguri", icon: Building2, category: "Bus Stand", district: "Darjeeling", aliases: ["sns", "siliguri bus stand", "bus terminus", "bus terminal"] },
  { name: "Hill Cart Road, Siliguri", icon: Building2, category: "Area", district: "Darjeeling", aliases: ["main road", "shopping"] },
  { name: "Sevoke Road, Siliguri", icon: Building2, category: "Area", district: "Darjeeling", aliases: ["main road"] },
  { name: "Matigara, Siliguri", icon: Building2, category: "Area", district: "Darjeeling" },
  { name: "Pradhan Nagar, Siliguri", icon: Building2, category: "Area", district: "Darjeeling" },
  { name: "Salugara, Siliguri", icon: Building2, category: "Area", district: "Darjeeling" },
  { name: "Salugara Monastery, Siliguri", icon: Landmark, category: "Monastery", district: "Darjeeling", aliases: ["buddhist", "kali mandir"] },
  { name: "Kharibari, Siliguri", icon: Building2, category: "Town", district: "Darjeeling" },
  { name: "Naxalbari, Siliguri", icon: Building2, category: "Town", district: "Darjeeling" },
  { name: "Phansidewa, Siliguri", icon: Building2, category: "Town", district: "Darjeeling" },
  { name: "Mahananda Wildlife Sanctuary", icon: TreePine, category: "Wildlife", district: "Darjeeling", aliases: ["latpanchor", "birding", "jungle"] },
  { name: "Coronation Bridge (Sevoke)", icon: Landmark, category: "Landmark", district: "Darjeeling", aliases: ["teesta bridge", "sevoke bridge"] },
  { name: "Teesta Bazaar, Siliguri", icon: Building2, category: "Area", district: "Darjeeling", aliases: ["river rafting", "teesta"] },
  
  // ==================== DOOARS REGION ====================
  { name: "Dooars, West Bengal", icon: TreePine, category: "Nature", district: "Jalpaiguri", aliases: ["doors to bhutan", "tea gardens", "jungle", "safari", "forest"] },
  { name: "Lataguri, Dooars", icon: TreePine, category: "Tourist", district: "Jalpaiguri", aliases: ["gorumara", "jungle", "safari", "resort"] },
  { name: "Murti, Dooars", icon: TreePine, category: "Tourist", district: "Jalpaiguri", aliases: ["river", "camping", "jungle"] },
  { name: "Samsing, Dooars", icon: TreePine, category: "Tourist", district: "Kalimpong", aliases: ["offbeat", "rocky island", "neora valley"] },
  { name: "Suntalekhola, Dooars", icon: TreePine, category: "Tourist", district: "Kalimpong", aliases: ["orange village", "homestay"] },
  { name: "Bindu, Dooars", icon: TreePine, category: "Tourist", district: "Kalimpong", aliases: ["indo bhutan border", "river", "offbeat"] },
  { name: "Rocky Island, Dooars", icon: TreePine, category: "Tourist", district: "Kalimpong", aliases: ["river", "picnic", "offbeat"] },
  { name: "Jhalong, Dooars", icon: TreePine, category: "Tourist", district: "Kalimpong", aliases: ["river rafting", "camping", "neora valley"] },
  { name: "Mendabari, Dooars", icon: TreePine, category: "Tourist", district: "Jalpaiguri", aliases: ["gorumara", "watchtower"] },
  { name: "Paren, Dooars", icon: TreePine, category: "Tourist", district: "Jalpaiguri", aliases: ["buxa", "offbeat"] },
  { name: "Totopara, Dooars", icon: Building2, category: "Village", district: "Alipurduar", aliases: ["toto tribe", "tribal village"] },
  
  // ==================== NEARBY CITIES (OUTSIDE WB) ====================
  { name: "Patna, Bihar", icon: Building2, category: "City", district: "Bihar", aliases: ["bihar capital", "patna junction"] },
  { name: "Ranchi, Jharkhand", icon: Building2, category: "City", district: "Jharkhand", aliases: ["jharkhand capital", "city of waterfalls"] },
  { name: "Jamshedpur, Jharkhand", icon: Building2, category: "City", district: "Jharkhand", aliases: ["tata nagar", "steel city"] },
  { name: "Dhanbad, Jharkhand", icon: Building2, category: "City", district: "Jharkhand", aliases: ["coal capital", "ism"] },
  { name: "Bhubaneswar, Odisha", icon: Building2, category: "City", district: "Odisha", aliases: ["odisha capital", "temple city"] },
  { name: "Puri, Odisha", icon: Landmark, category: "Pilgrimage", district: "Odisha", aliases: ["jagannath", "sea beach", "rath yatra", "religious"] },
  { name: "Guwahati, Assam", icon: Building2, category: "City", district: "Assam", aliases: ["assam", "gateway to northeast", "kamakhya"] },
  { name: "Shillong, Meghalaya", icon: TreePine, category: "Hill Station", district: "Meghalaya", aliases: ["scotland of east", "meghalaya capital"] },
  { name: "Gangtok, Sikkim", icon: TreePine, category: "Hill Station", district: "Sikkim", aliases: ["sikkim capital", "himalaya", "buddhist"] },
  { name: "Varanasi, Uttar Pradesh", icon: Landmark, category: "Pilgrimage", district: "Uttar Pradesh", aliases: ["kashi", "banaras", "ganga aarti", "religious", "oldest city"] },
  { name: "Delhi", icon: Building2, category: "City", district: "Delhi", aliases: ["capital", "new delhi", "igdtuw"] },
  { name: "Mumbai", icon: Building2, category: "City", district: "Maharashtra", aliases: ["bombay", "financial capital", "bollywood"] },
  { name: "Bangalore", icon: Building2, category: "City", district: "Karnataka", aliases: ["bengaluru", "silicon valley", "it city", "garden city"] },
  { name: "Chennai", icon: Building2, category: "City", district: "Tamil Nadu", aliases: ["madras", "south india"] },
  { name: "Hyderabad", icon: Building2, category: "City", district: "Telangana", aliases: ["city of pearls", "biryani", "it city"] },
];

// Search function with alias support
export function searchLocations(query: string): Location[] {
  if (!query.trim()) return westBengalLocations;
  
  const searchTerm = query.toLowerCase().trim();
  
  return westBengalLocations.filter(loc => {
    // Search in name
    if (loc.name.toLowerCase().includes(searchTerm)) return true;
    
    // Search in category
    if (loc.category.toLowerCase().includes(searchTerm)) return true;
    
    // Search in district
    if (loc.district.toLowerCase().includes(searchTerm)) return true;
    
    // Search in aliases
    if (loc.aliases?.some(alias => alias.toLowerCase().includes(searchTerm))) return true;
    
    return false;
  });
}
