# Blackbox Deploy - Application Configuration
# Simple deployment configuration for RideShare Hub

runtime: nodejs22
env: standard

# Instance configuration
instance_class: F2  # 2 CPU, 512MB memory

# Automatic scaling
automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.65

# Environment variables
env_variables:
  NODE_ENV: 'production'
  PORT: '5000'

# Handlers
handlers:
  # Serve static files from dist/public
  - url: /assets
    static_dir: dist/public/assets
    secure: always
    
  - url: /.*
    script: auto
    secure: always

# Health check
health_check:
  enable_health_check: true
  check_interval_sec: 30
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2
  restart_threshold: 60
  host: 0.0.0.0

# Liveness check
liveness_check:
  path: "/api/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

# Readiness check
readiness_check:
  path: "/api/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300
